import type { CaddyRoute, CaddyState } from "@dokploy/server";
import { renderCaddyfile } from "@dokploy/server";
import { beforeAll, describe, expect, test } from "vitest";
import { hasOpenSsl, issueCertificate } from "./certificate";

const route = (overrides: Partial<CaddyRoute> = {}): CaddyRoute => ({
	host: "app.test",
	https: true,
	path: null,
	stripPrefix: null,
	addPrefix: null,
	uniqueConfigKey: 1,
	upstreams: ["app:3001"],
	users: [],
	redirects: [],
	...overrides,
});
const render = (routes: CaddyRoute[], extra: Partial<CaddyState> = {}) =>
	renderCaddyfile({ certificates: [], routes, ...extra });
const redirect = (
	overrides: Partial<CaddyRoute["redirects"][number]> = {},
) => ({
	regex: "^https?://app\\.test/(.*)",
	replacement: "https://else.test/$1",
	permanent: true,
	uniqueConfigKey: 7,
	...overrides,
});

test("one HTTPS application with email renders a complete Caddyfile", () => {
	expect(
		render([route()], { email: "ops@example.com" }).caddyfile,
	).toBe(`# Generated by Dokploy from the database. Edits here are overwritten.
# Your own configuration belongs in global/*.caddy and sites/*.caddy.
{
	email ops@example.com
	import global/*.caddy
	admin localhost:2019
}
import sites/*.caddy
https://app.test {
	reverse_proxy app:3001 {
		header_up X-Real-IP {client_ip}
		header_up X-Forwarded-Port {http.request.local.port}
		stream_close_delay 24h
	}
}
http:// {
	respond 404
}
`);
});

test("shared root and API routes render a complete ordered Caddyfile", () => {
	const api = route({
		path: "/api",
		stripPrefix: "/api",
		addPrefix: "/v1",
		uniqueConfigKey: 2,
		upstreams: ["api:3002"],
		users: [{ username: "ops", hash: "$2b$10$hash" }],
		redirects: [redirect()],
	});
	expect(
		render([route(), api]).caddyfile,
	).toBe(`# Generated by Dokploy from the database. Edits here are overwritten.
# Your own configuration belongs in global/*.caddy and sites/*.caddy.
{
	import global/*.caddy
	admin localhost:2019
}
import sites/*.caddy
https://app.test {
	route {
		@path_2 path_regexp \`^/api\`
		handle @path_2 {
			route {
				@glued_2 path_regexp \`^/api[^/]\`
				uri @glued_2 path_regexp \`^/api\` \`/api/\`
				uri strip_prefix \`/api\`
				request_header X-Forwarded-Prefix \`/api\`
				uri path_regexp ^ \`/v1\`
				vars dokploy_url {scheme}://{hostport}{uri}
				map {method} {dokploy_permanent} {dokploy_temporary} {
					GET 301 302
					default 308 307
				}
				@redirect_7 vars_regexp redirect_7 dokploy_url \`^https?://app\\.test/(.*)\`
				route @redirect_7 {
					@around vars_regexp redirect_7_around dokploy_url \`^(?P<dokploy_before>.*?)(?:^https?://app\\.test/(.*))(?P<dokploy_after>.*)$\`
					route @around {
						vars dokploy_target \`{re.redirect_7_around.dokploy_before}https://else.test/{re.redirect_7.1}{re.redirect_7_around.dokploy_after}\`
						@changed not vars dokploy_target {vars.dokploy_url}
						redir @changed {vars.dokploy_target} {dokploy_permanent}
					}
				}
				basic_auth {
					\`ops\` \`$2b$10$hash\`
				}
				request_header -Authorization
				reverse_proxy api:3002 {
					header_up X-Real-IP {client_ip}
					header_up X-Forwarded-Port {http.request.local.port}
					stream_close_delay 24h
				}
			}
		}
		handle {
			reverse_proxy app:3001 {
				header_up X-Real-IP {client_ip}
				header_up X-Forwarded-Port {http.request.local.port}
				stream_close_delay 24h
			}
		}
	}
}
http:// {
	respond 404
}
`);
});

test("longest paths lead and regex characters are escaped in case-sensitive matchers", () => {
	const text = render([
		route({ path: "/a", uniqueConfigKey: 1 }),
		route({ path: "/a.b(c)", uniqueConfigKey: 2 }),
	]).caddyfile;
	expect(text.indexOf("@path_2 path_regexp")).toBeLessThan(
		text.indexOf("@path_1 path_regexp"),
	);
	expect(text).toContain("@path_2 path_regexp `^/a\\.b\\(c\\)`");
	expect(text).not.toContain("@path_2 path `");
});

test("path-only hosts end in a 404 handle", () => {
	expect(render([route({ path: "/api" })]).caddyfile).toContain(
		"\t\thandle {\n\t\t\trespond 404\n\t\t}",
	);
});

test("strip and add preserve glued slashes and escape dollars", () => {
	const text = render([
		route({ path: "/api", stripPrefix: "/api", addPrefix: "/v$1" }),
	]).caddyfile;
	expect(text).toContain("uri @glued_1 path_regexp `^/api` `/api/`");
	expect(text).toContain("uri strip_prefix `/api`");
	expect(text).toContain("request_header X-Forwarded-Prefix `/api`");
	expect(text).toContain("uri path_regexp ^ `/v$$1`");
});

test("Go redirect captures, named groups and dollars use method-specific status", () => {
	const text = render([
		route({
			redirects: [
				redirect({
					regex: "(?P<rest>.*)",
					replacement: "${1}/$1/${rest}/$0/$9/$$",
					permanent: false,
				}),
			],
		}),
	]).caddyfile;
	// The pattern stands alone in the first matcher, so its groups keep their
	// numbers and a reference to one it does not have is empty, as in Go.
	expect(text).toContain(
		"@redirect_7 vars_regexp redirect_7 dokploy_url `(?P<rest>.*)`",
	);
	expect(text).toContain(
		"{re.redirect_7.1}/{re.redirect_7.1}/{re.redirect_7.rest}/{re.redirect_7.0}/{re.redirect_7.9}/$",
	);
	expect(text).toContain("GET 301 302\n\t\t\tdefault 308 307");
	expect(text).toContain(
		"redir @changed {vars.dokploy_target} {dokploy_temporary}",
	);
	expect(text).toContain("@changed not vars dokploy_target {vars.dokploy_url}");
});

test("HTTP-only sites stay HTTP and mixed sites redirect HTTPS paths", () => {
	const text = render([
		route({ https: false }),
		route({ path: "/secure", uniqueConfigKey: 2 }),
	]).caddyfile;
	expect(text).toContain("http://app.test {");
	expect(text).toContain(
		"@path_2 path_regexp `^/secure`\n\t\thandle @path_2 {\n\t\t\tredir https://{host}{uri} 308",
	);
});

test("international hosts become punycode and invalid hosts are refused", () => {
	const bad = ["bad host", "bad{host}", "bad.test\nrespond pwned"].map((host) =>
		route({ host }),
	);
	const { caddyfile, refused } = render([route({ host: "тест.test" }), ...bad]);
	expect(caddyfile).toContain("https://xn--e1aybc.test {");
	for (const item of bad) expect(caddyfile).not.toContain(item.host);
	expect(caddyfile).not.toContain("pwned");
	expect(refused).toEqual(bad);
});

test("an HTTPS host named like a directive is still written as a host", () => {
	expect(render([route({ host: "import" })]).caddyfile).toContain(
		"\nhttps://import {\n",
	);
});

test("unsupported routes answer 503 in their own place", () => {
	const text = render([
		route({
			path: "/sso",
			unsupported: "Forward auth is not available with Caddy",
		}),
		route({ path: "/ok", uniqueConfigKey: 2 }),
	]).caddyfile;
	expect(text).toContain(
		"handle @path_1 {\n\t\t\trespond `Forward auth is not available with Caddy` 503",
	);
	expect(text).toContain("reverse_proxy app:3001");
	expect(text.split("reverse_proxy")).toHaveLength(2);
});

test("hostile upstream answers 503 without writing its directive", () => {
	const bad = route({ upstreams: ["app:3001\nrespond pwned"] });
	const { caddyfile, refused } = render([bad]);
	expect(caddyfile).toContain(
		"respond `This domain has a setting Caddy cannot use` 503",
	);
	expect(caddyfile).not.toContain("pwned");
	expect(refused).toEqual([bad]);
});

test("redirect regex with parse-time environment expansion answers 503", () => {
	const bad = route({ redirects: [redirect({ regex: "{$HOME}" })] });
	const { caddyfile, refused } = render([bad]);
	expect(caddyfile).toContain(
		"respond `This domain has a setting Caddy cannot use` 503",
	);
	expect(caddyfile).not.toContain("{$HOME}");
	expect(refused).toEqual([bad]);
});

test("unwritable path refuses its entire host including a sibling", () => {
	const bad = route({ path: "/bad`" });
	const { caddyfile, refused } = render([
		bad,
		route({ path: "/ok", uniqueConfigKey: 2 }),
	]);
	expect(caddyfile).toContain(
		"app.test {\n\trespond `This domain has a setting Caddy cannot use` 503\n}",
	);
	expect(caddyfile).not.toContain("reverse_proxy app:3001");
	expect(refused).toEqual([bad]);
});

test("placeholder braces in usernames and redirect replacements stay literal", () => {
	const { caddyfile, refused } = render([
		route({
			users: [{ username: "{env.HOME}", hash: "hash" }],
			redirects: [redirect({ replacement: "https://else.test/{env.HOME}" })],
		}),
	]);
	expect(caddyfile).toContain("`\\{env.HOME}` `hash`");
	expect(caddyfile).toContain("https://else.test/\\{env.HOME}");
	expect(refused).toEqual([]);
});

describe.skipIf(!hasOpenSsl())("uploaded certificates", () => {
	let certificateData = "";
	let privateKey = "";
	let otherKey = "";
	beforeAll(() => {
		({ certificate: certificateData, key: privateKey } = issueCertificate([
			"cert.test",
			"*.wild.test",
		]));
		otherKey = issueCertificate(["other.test"]).key;
	});
	test("matching certificate and wildcard use their TLS paths", () => {
		const cert = {
			certFile: "/certs/chain.crt",
			keyFile: "/certs/privkey.key",
			certificateData,
			privateKey,
		};
		const text = render(
			[route({ host: "cert.test" }), route({ host: "a.wild.test" })],
			{ certificates: [cert] },
		).caddyfile;
		expect(
			text.split("tls `/certs/chain.crt` `/certs/privkey.key`"),
		).toHaveLength(3);
	});
	test("placeholder braces in a certificate's path stay literal", () => {
		const text = render([route({ host: "cert.test" })], {
			certificates: [
				{
					certFile: "/certs/{env.HOME}/chain.crt",
					keyFile: "/certs/{env.HOME}/privkey.key",
					certificateData,
					privateKey,
				},
			],
		}).caddyfile;
		expect(text).toContain(
			"tls `/certs/\\{env.HOME}/chain.crt` `/certs/\\{env.HOME}/privkey.key`",
		);
	});
	test("mismatched key and garbage certificate do not produce TLS lines", () => {
		const cert = {
			certFile: "/certs/chain.crt",
			keyFile: "/certs/privkey.key",
			certificateData,
			privateKey: otherKey,
		};
		const text = render([route({ host: "cert.test" })], {
			certificates: [cert, { ...cert, certificateData: "garbage", privateKey }],
		}).caddyfile;
		expect(text).not.toContain("tls ");
	});
});

test("a host with no certificate provider falls back to Caddy's own authority", () => {
	const { caddyfile, automatic } = render([
		route({ host: "none.test", selfSigned: true }),
		route({ host: "public.test", uniqueConfigKey: 2 }),
		route({ host: "plain.test", https: false, selfSigned: true }),
	]);
	expect(caddyfile).toContain(
		"https://none.test {\n\ttls {\n\t\tissuer acme\n\t\tissuer internal\n\t}\n",
	);
	expect(caddyfile.split("issuer internal")).toHaveLength(2);
	// Only this one stays unanswered over HTTPS until a certificate arrives.
	expect(automatic).toEqual(["public.test"]);
});

test("global admin stays last, invalid email is omitted and catch-all closes file", () => {
	const text = render([], { email: "ops@example.com\nadmin off" }).caddyfile;
	expect(text).toContain("\timport global/*.caddy\n\tadmin localhost:2019\n}");
	expect(text).not.toContain("email ");
	expect(text.endsWith("http:// {\n\trespond 404\n}\n")).toBe(true);
});

test("same state renders identically and hosts are sorted", () => {
	const state = [route({ host: "z.test" }), route({ host: "a.test" })];
	const text = render(state).caddyfile;
	expect(render(state).caddyfile).toBe(text);
	expect(text.indexOf("a.test {")).toBeLessThan(text.indexOf("z.test {"));
});
