services:
  macos:
    image: dockurr/macos:1.14
    volumes:
    - macos-storage:/storage
    environment:
      - VERSION
    devices:
      # If in .env string 'KVM=N' is not commented, you need to comment line below
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m

volumes:
  macos-storage: