version: "3.8"
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.48.1
    restart: always
    networks:
      - dokploy-network
    ports:
      - ${N8N_PORT}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${HASH}.rule=Host(`${N8N_HOST}`)
      - traefik.http.services.${HASH}.loadbalancer.server.port=${N8N_PORT}
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=https://${N8N_HOST}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: 
networks:
  dokploy-network:
    external: true