version: "3.7"
services:
  pocketbase:
    image: spectado/pocketbase:latest
    restart: unless-stopped
    ports:
      - ${POCKETBASE_PORT}
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.${HASH}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${HASH}.entrypoints=websecure
      - traefik.http.routers.${HASH}.tls.certResolver=letsencrypt
      - traefik.http.services.${HASH}.loadbalancer.server.port=${POCKETBASE_PORT}
    volumes:
      - /etc/dokploy/templates/${HASH}/data:/pb_data
      - /etc/dokploy/templates/${HASH}/public:/pb_public
      - /etc/dokploy/templates/${HASH}/migrations:/pb_migrations

networks:
  dokploy-network:
    external: true