/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as InvitationRouteImport } from './routes/invitation'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SendResetPasswordRouteImport } from './routes/send-reset-password'
import { Route as SwaggerRouteImport } from './routes/swagger'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation/$invitationId'
import { Route as DashboardDeploymentsRouteImport } from './routes/dashboard/deployments'
import { Route as DashboardDockerRouteImport } from './routes/dashboard/docker'
import { Route as DashboardHomeRouteImport } from './routes/dashboard/home'
import { Route as DashboardMonitoringRouteImport } from './routes/dashboard/monitoring'
import { Route as DashboardNetworksRouteImport } from './routes/dashboard/networks'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard/projects'
import { Route as DashboardRequestsRouteImport } from './routes/dashboard/requests'
import { Route as DashboardSchedulesRouteImport } from './routes/dashboard/schedules'
import { Route as DashboardSwarmRouteImport } from './routes/dashboard/swarm'
import { Route as DashboardTraefikRouteImport } from './routes/dashboard/traefik'
import { Route as DashboardSettingsAiRouteImport } from './routes/dashboard/settings/ai'
import { Route as DashboardSettingsAuditLogsRouteImport } from './routes/dashboard/settings/audit-logs'
import { Route as DashboardSettingsBillingRouteImport } from './routes/dashboard/settings/billing'
import { Route as DashboardSettingsCertificatesRouteImport } from './routes/dashboard/settings/certificates'
import { Route as DashboardSettingsClusterRouteImport } from './routes/dashboard/settings/cluster'
import { Route as DashboardSettingsDeploymentsRouteImport } from './routes/dashboard/settings/deployments'
import { Route as DashboardSettingsDestinationsRouteImport } from './routes/dashboard/settings/destinations'
import { Route as DashboardSettingsGitProvidersRouteImport } from './routes/dashboard/settings/git-providers'
import { Route as DashboardSettingsInvoicesRouteImport } from './routes/dashboard/settings/invoices'
import { Route as DashboardSettingsLicenseRouteImport } from './routes/dashboard/settings/license'
import { Route as DashboardSettingsNotificationsRouteImport } from './routes/dashboard/settings/notifications'
import { Route as DashboardSettingsProfileRouteImport } from './routes/dashboard/settings/profile'
import { Route as DashboardSettingsRegistryRouteImport } from './routes/dashboard/settings/registry'
import { Route as DashboardSettingsSecretsRouteImport } from './routes/dashboard/settings/secrets'
import { Route as DashboardSettingsServerRouteImport } from './routes/dashboard/settings/server'
import { Route as DashboardSettingsServersRouteImport } from './routes/dashboard/settings/servers'
import { Route as DashboardSettingsSshKeysRouteImport } from './routes/dashboard/settings/ssh-keys'
import { Route as DashboardSettingsSsoRouteImport } from './routes/dashboard/settings/sso'
import { Route as DashboardSettingsTagsRouteImport } from './routes/dashboard/settings/tags'
import { Route as DashboardSettingsUsersRouteImport } from './routes/dashboard/settings/users'
import { Route as DashboardSettingsWhitelabelingRouteImport } from './routes/dashboard/settings/whitelabeling'
import { Route as DashboardProjectProjectIdEnvironmentEnvironmentIdIndexRouteImport } from './routes/dashboard/project/$projectId/environment/$environmentId/index'
import { Route as DashboardProjectProjectIdEnvironmentEnvironmentIdServicesApplicationApplicationIdRouteImport } from './routes/dashboard/project/$projectId/environment/$environmentId/services/application/$applicationId'
import { Route as DashboardProjectProjectIdEnvironmentEnvironmentIdServicesComposeComposeIdRouteImport } from './routes/dashboard/project/$projectId/environment/$environmentId/services/compose/$composeId'
import { Route as DashboardProjectProjectIdEnvironmentEnvironmentIdServicesLibsqlLibsqlIdRouteImport } from './routes/dashboard/project/$projectId/environment/$environmentId/services/libsql/$libsqlId'
import { Route as DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMariadbMariadbIdRouteImport } from './routes/dashboard/project/$projectId/environment/$environmentId/services/mariadb/$mariadbId'
import { Route as DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMongoMongoIdRouteImport } from './routes/dashboard/project/$projectId/environment/$environmentId/services/mongo/$mongoId'
import { Route as DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMysqlMysqlIdRouteImport } from './routes/dashboard/project/$projectId/environment/$environmentId/services/mysql/$mysqlId'
import { Route as DashboardProjectProjectIdEnvironmentEnvironmentIdServicesPostgresPostgresIdRouteImport } from './routes/dashboard/project/$projectId/environment/$environmentId/services/postgres/$postgresId'
import { Route as DashboardProjectProjectIdEnvironmentEnvironmentIdServicesRedisRedisIdRouteImport } from './routes/dashboard/project/$projectId/environment/$environmentId/services/redis/$redisId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationRoute = InvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SendResetPasswordRoute = SendResetPasswordRouteImport.update({
  id: '/send-reset-password',
  path: '/send-reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SwaggerRoute = SwaggerRouteImport.update({
  id: '/swagger',
  path: '/swagger',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardDeploymentsRoute = DashboardDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDockerRoute = DashboardDockerRouteImport.update({
  id: '/docker',
  path: '/docker',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMonitoringRoute = DashboardMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNetworksRoute = DashboardNetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRequestsRoute = DashboardRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSchedulesRoute = DashboardSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSwarmRoute = DashboardSwarmRouteImport.update({
  id: '/swarm',
  path: '/swarm',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTraefikRoute = DashboardTraefikRouteImport.update({
  id: '/traefik',
  path: '/traefik',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsAiRoute = DashboardSettingsAiRouteImport.update({
  id: '/settings/ai',
  path: '/settings/ai',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsAuditLogsRoute =
  DashboardSettingsAuditLogsRouteImport.update({
    id: '/settings/audit-logs',
    path: '/settings/audit-logs',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsBillingRoute =
  DashboardSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsCertificatesRoute =
  DashboardSettingsCertificatesRouteImport.update({
    id: '/settings/certificates',
    path: '/settings/certificates',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsClusterRoute =
  DashboardSettingsClusterRouteImport.update({
    id: '/settings/cluster',
    path: '/settings/cluster',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsDeploymentsRoute =
  DashboardSettingsDeploymentsRouteImport.update({
    id: '/settings/deployments',
    path: '/settings/deployments',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsDestinationsRoute =
  DashboardSettingsDestinationsRouteImport.update({
    id: '/settings/destinations',
    path: '/settings/destinations',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsGitProvidersRoute =
  DashboardSettingsGitProvidersRouteImport.update({
    id: '/settings/git-providers',
    path: '/settings/git-providers',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsInvoicesRoute =
  DashboardSettingsInvoicesRouteImport.update({
    id: '/settings/invoices',
    path: '/settings/invoices',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsLicenseRoute =
  DashboardSettingsLicenseRouteImport.update({
    id: '/settings/license',
    path: '/settings/license',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsNotificationsRoute =
  DashboardSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsRegistryRoute =
  DashboardSettingsRegistryRouteImport.update({
    id: '/settings/registry',
    path: '/settings/registry',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsSecretsRoute =
  DashboardSettingsSecretsRouteImport.update({
    id: '/settings/secrets',
    path: '/settings/secrets',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsServerRoute = DashboardSettingsServerRouteImport.update({
  id: '/settings/server',
  path: '/settings/server',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsServersRoute =
  DashboardSettingsServersRouteImport.update({
    id: '/settings/servers',
    path: '/settings/servers',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsSshKeysRoute =
  DashboardSettingsSshKeysRouteImport.update({
    id: '/settings/ssh-keys',
    path: '/settings/ssh-keys',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsSsoRoute = DashboardSettingsSsoRouteImport.update({
  id: '/settings/sso',
  path: '/settings/sso',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsTagsRoute = DashboardSettingsTagsRouteImport.update({
  id: '/settings/tags',
  path: '/settings/tags',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsUsersRoute = DashboardSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsWhitelabelingRoute =
  DashboardSettingsWhitelabelingRouteImport.update({
    id: '/settings/whitelabeling',
    path: '/settings/whitelabeling',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProjectProjectIdEnvironmentEnvironmentIdIndexRoute =
  DashboardProjectProjectIdEnvironmentEnvironmentIdIndexRouteImport.update({
    id: '/project/$projectId/environment/$environmentId/',
    path: '/project/$projectId/environment/$environmentId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProjectProjectIdEnvironmentEnvironmentIdServicesApplicationApplicationIdRoute =
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesApplicationApplicationIdRouteImport.update(
    {
      id: '/project/$projectId/environment/$environmentId/services/application/$applicationId',
      path: '/project/$projectId/environment/$environmentId/services/application/$applicationId',
      getParentRoute: () => DashboardRouteRoute,
    } as any,
  )
const DashboardProjectProjectIdEnvironmentEnvironmentIdServicesComposeComposeIdRoute =
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesComposeComposeIdRouteImport.update(
    {
      id: '/project/$projectId/environment/$environmentId/services/compose/$composeId',
      path: '/project/$projectId/environment/$environmentId/services/compose/$composeId',
      getParentRoute: () => DashboardRouteRoute,
    } as any,
  )
const DashboardProjectProjectIdEnvironmentEnvironmentIdServicesLibsqlLibsqlIdRoute =
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesLibsqlLibsqlIdRouteImport.update(
    {
      id: '/project/$projectId/environment/$environmentId/services/libsql/$libsqlId',
      path: '/project/$projectId/environment/$environmentId/services/libsql/$libsqlId',
      getParentRoute: () => DashboardRouteRoute,
    } as any,
  )
const DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMariadbMariadbIdRoute =
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMariadbMariadbIdRouteImport.update(
    {
      id: '/project/$projectId/environment/$environmentId/services/mariadb/$mariadbId',
      path: '/project/$projectId/environment/$environmentId/services/mariadb/$mariadbId',
      getParentRoute: () => DashboardRouteRoute,
    } as any,
  )
const DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMongoMongoIdRoute =
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMongoMongoIdRouteImport.update(
    {
      id: '/project/$projectId/environment/$environmentId/services/mongo/$mongoId',
      path: '/project/$projectId/environment/$environmentId/services/mongo/$mongoId',
      getParentRoute: () => DashboardRouteRoute,
    } as any,
  )
const DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMysqlMysqlIdRoute =
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMysqlMysqlIdRouteImport.update(
    {
      id: '/project/$projectId/environment/$environmentId/services/mysql/$mysqlId',
      path: '/project/$projectId/environment/$environmentId/services/mysql/$mysqlId',
      getParentRoute: () => DashboardRouteRoute,
    } as any,
  )
const DashboardProjectProjectIdEnvironmentEnvironmentIdServicesPostgresPostgresIdRoute =
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesPostgresPostgresIdRouteImport.update(
    {
      id: '/project/$projectId/environment/$environmentId/services/postgres/$postgresId',
      path: '/project/$projectId/environment/$environmentId/services/postgres/$postgresId',
      getParentRoute: () => DashboardRouteRoute,
    } as any,
  )
const DashboardProjectProjectIdEnvironmentEnvironmentIdServicesRedisRedisIdRoute =
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesRedisRedisIdRouteImport.update(
    {
      id: '/project/$projectId/environment/$environmentId/services/redis/$redisId',
      path: '/project/$projectId/environment/$environmentId/services/redis/$redisId',
      getParentRoute: () => DashboardRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/invitation': typeof InvitationRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/send-reset-password': typeof SendResetPasswordRoute
  '/swagger': typeof SwaggerRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/dashboard/deployments': typeof DashboardDeploymentsRoute
  '/dashboard/docker': typeof DashboardDockerRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/networks': typeof DashboardNetworksRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/schedules': typeof DashboardSchedulesRoute
  '/dashboard/swarm': typeof DashboardSwarmRoute
  '/dashboard/traefik': typeof DashboardTraefikRoute
  '/dashboard/settings/ai': typeof DashboardSettingsAiRoute
  '/dashboard/settings/audit-logs': typeof DashboardSettingsAuditLogsRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/certificates': typeof DashboardSettingsCertificatesRoute
  '/dashboard/settings/cluster': typeof DashboardSettingsClusterRoute
  '/dashboard/settings/deployments': typeof DashboardSettingsDeploymentsRoute
  '/dashboard/settings/destinations': typeof DashboardSettingsDestinationsRoute
  '/dashboard/settings/git-providers': typeof DashboardSettingsGitProvidersRoute
  '/dashboard/settings/invoices': typeof DashboardSettingsInvoicesRoute
  '/dashboard/settings/license': typeof DashboardSettingsLicenseRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/registry': typeof DashboardSettingsRegistryRoute
  '/dashboard/settings/secrets': typeof DashboardSettingsSecretsRoute
  '/dashboard/settings/server': typeof DashboardSettingsServerRoute
  '/dashboard/settings/servers': typeof DashboardSettingsServersRoute
  '/dashboard/settings/ssh-keys': typeof DashboardSettingsSshKeysRoute
  '/dashboard/settings/sso': typeof DashboardSettingsSsoRoute
  '/dashboard/settings/tags': typeof DashboardSettingsTagsRoute
  '/dashboard/settings/users': typeof DashboardSettingsUsersRoute
  '/dashboard/settings/whitelabeling': typeof DashboardSettingsWhitelabelingRoute
  '/dashboard/project/$projectId/environment/$environmentId/': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdIndexRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/application/$applicationId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesApplicationApplicationIdRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/compose/$composeId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesComposeComposeIdRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/libsql/$libsqlId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesLibsqlLibsqlIdRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/mariadb/$mariadbId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMariadbMariadbIdRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/mongo/$mongoId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMongoMongoIdRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/mysql/$mysqlId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMysqlMysqlIdRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/postgres/$postgresId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesPostgresPostgresIdRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/redis/$redisId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesRedisRedisIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/invitation': typeof InvitationRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/send-reset-password': typeof SendResetPasswordRoute
  '/swagger': typeof SwaggerRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/dashboard/deployments': typeof DashboardDeploymentsRoute
  '/dashboard/docker': typeof DashboardDockerRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/networks': typeof DashboardNetworksRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/schedules': typeof DashboardSchedulesRoute
  '/dashboard/swarm': typeof DashboardSwarmRoute
  '/dashboard/traefik': typeof DashboardTraefikRoute
  '/dashboard/settings/ai': typeof DashboardSettingsAiRoute
  '/dashboard/settings/audit-logs': typeof DashboardSettingsAuditLogsRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/certificates': typeof DashboardSettingsCertificatesRoute
  '/dashboard/settings/cluster': typeof DashboardSettingsClusterRoute
  '/dashboard/settings/deployments': typeof DashboardSettingsDeploymentsRoute
  '/dashboard/settings/destinations': typeof DashboardSettingsDestinationsRoute
  '/dashboard/settings/git-providers': typeof DashboardSettingsGitProvidersRoute
  '/dashboard/settings/invoices': typeof DashboardSettingsInvoicesRoute
  '/dashboard/settings/license': typeof DashboardSettingsLicenseRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/registry': typeof DashboardSettingsRegistryRoute
  '/dashboard/settings/secrets': typeof DashboardSettingsSecretsRoute
  '/dashboard/settings/server': typeof DashboardSettingsServerRoute
  '/dashboard/settings/servers': typeof DashboardSettingsServersRoute
  '/dashboard/settings/ssh-keys': typeof DashboardSettingsSshKeysRoute
  '/dashboard/settings/sso': typeof DashboardSettingsSsoRoute
  '/dashboard/settings/tags': typeof DashboardSettingsTagsRoute
  '/dashboard/settings/users': typeof DashboardSettingsUsersRoute
  '/dashboard/settings/whitelabeling': typeof DashboardSettingsWhitelabelingRoute
  '/dashboard/project/$projectId/environment/$environmentId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdIndexRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/application/$applicationId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesApplicationApplicationIdRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/compose/$composeId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesComposeComposeIdRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/libsql/$libsqlId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesLibsqlLibsqlIdRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/mariadb/$mariadbId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMariadbMariadbIdRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/mongo/$mongoId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMongoMongoIdRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/mysql/$mysqlId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMysqlMysqlIdRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/postgres/$postgresId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesPostgresPostgresIdRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/redis/$redisId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesRedisRedisIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/invitation': typeof InvitationRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/send-reset-password': typeof SendResetPasswordRoute
  '/swagger': typeof SwaggerRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/dashboard/deployments': typeof DashboardDeploymentsRoute
  '/dashboard/docker': typeof DashboardDockerRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/networks': typeof DashboardNetworksRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/schedules': typeof DashboardSchedulesRoute
  '/dashboard/swarm': typeof DashboardSwarmRoute
  '/dashboard/traefik': typeof DashboardTraefikRoute
  '/dashboard/settings/ai': typeof DashboardSettingsAiRoute
  '/dashboard/settings/audit-logs': typeof DashboardSettingsAuditLogsRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/certificates': typeof DashboardSettingsCertificatesRoute
  '/dashboard/settings/cluster': typeof DashboardSettingsClusterRoute
  '/dashboard/settings/deployments': typeof DashboardSettingsDeploymentsRoute
  '/dashboard/settings/destinations': typeof DashboardSettingsDestinationsRoute
  '/dashboard/settings/git-providers': typeof DashboardSettingsGitProvidersRoute
  '/dashboard/settings/invoices': typeof DashboardSettingsInvoicesRoute
  '/dashboard/settings/license': typeof DashboardSettingsLicenseRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/registry': typeof DashboardSettingsRegistryRoute
  '/dashboard/settings/secrets': typeof DashboardSettingsSecretsRoute
  '/dashboard/settings/server': typeof DashboardSettingsServerRoute
  '/dashboard/settings/servers': typeof DashboardSettingsServersRoute
  '/dashboard/settings/ssh-keys': typeof DashboardSettingsSshKeysRoute
  '/dashboard/settings/sso': typeof DashboardSettingsSsoRoute
  '/dashboard/settings/tags': typeof DashboardSettingsTagsRoute
  '/dashboard/settings/users': typeof DashboardSettingsUsersRoute
  '/dashboard/settings/whitelabeling': typeof DashboardSettingsWhitelabelingRoute
  '/dashboard/project/$projectId/environment/$environmentId/': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdIndexRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/application/$applicationId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesApplicationApplicationIdRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/compose/$composeId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesComposeComposeIdRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/libsql/$libsqlId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesLibsqlLibsqlIdRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/mariadb/$mariadbId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMariadbMariadbIdRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/mongo/$mongoId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMongoMongoIdRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/mysql/$mysqlId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMysqlMysqlIdRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/postgres/$postgresId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesPostgresPostgresIdRoute
  '/dashboard/project/$projectId/environment/$environmentId/services/redis/$redisId': typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesRedisRedisIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/invitation'
    | '/register'
    | '/reset-password'
    | '/send-reset-password'
    | '/swagger'
    | '/accept-invitation/$invitationId'
    | '/dashboard/deployments'
    | '/dashboard/docker'
    | '/dashboard/home'
    | '/dashboard/monitoring'
    | '/dashboard/networks'
    | '/dashboard/projects'
    | '/dashboard/requests'
    | '/dashboard/schedules'
    | '/dashboard/swarm'
    | '/dashboard/traefik'
    | '/dashboard/settings/ai'
    | '/dashboard/settings/audit-logs'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/certificates'
    | '/dashboard/settings/cluster'
    | '/dashboard/settings/deployments'
    | '/dashboard/settings/destinations'
    | '/dashboard/settings/git-providers'
    | '/dashboard/settings/invoices'
    | '/dashboard/settings/license'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/registry'
    | '/dashboard/settings/secrets'
    | '/dashboard/settings/server'
    | '/dashboard/settings/servers'
    | '/dashboard/settings/ssh-keys'
    | '/dashboard/settings/sso'
    | '/dashboard/settings/tags'
    | '/dashboard/settings/users'
    | '/dashboard/settings/whitelabeling'
    | '/dashboard/project/$projectId/environment/$environmentId/'
    | '/dashboard/project/$projectId/environment/$environmentId/services/application/$applicationId'
    | '/dashboard/project/$projectId/environment/$environmentId/services/compose/$composeId'
    | '/dashboard/project/$projectId/environment/$environmentId/services/libsql/$libsqlId'
    | '/dashboard/project/$projectId/environment/$environmentId/services/mariadb/$mariadbId'
    | '/dashboard/project/$projectId/environment/$environmentId/services/mongo/$mongoId'
    | '/dashboard/project/$projectId/environment/$environmentId/services/mysql/$mysqlId'
    | '/dashboard/project/$projectId/environment/$environmentId/services/postgres/$postgresId'
    | '/dashboard/project/$projectId/environment/$environmentId/services/redis/$redisId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/invitation'
    | '/register'
    | '/reset-password'
    | '/send-reset-password'
    | '/swagger'
    | '/accept-invitation/$invitationId'
    | '/dashboard/deployments'
    | '/dashboard/docker'
    | '/dashboard/home'
    | '/dashboard/monitoring'
    | '/dashboard/networks'
    | '/dashboard/projects'
    | '/dashboard/requests'
    | '/dashboard/schedules'
    | '/dashboard/swarm'
    | '/dashboard/traefik'
    | '/dashboard/settings/ai'
    | '/dashboard/settings/audit-logs'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/certificates'
    | '/dashboard/settings/cluster'
    | '/dashboard/settings/deployments'
    | '/dashboard/settings/destinations'
    | '/dashboard/settings/git-providers'
    | '/dashboard/settings/invoices'
    | '/dashboard/settings/license'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/registry'
    | '/dashboard/settings/secrets'
    | '/dashboard/settings/server'
    | '/dashboard/settings/servers'
    | '/dashboard/settings/ssh-keys'
    | '/dashboard/settings/sso'
    | '/dashboard/settings/tags'
    | '/dashboard/settings/users'
    | '/dashboard/settings/whitelabeling'
    | '/dashboard/project/$projectId/environment/$environmentId'
    | '/dashboard/project/$projectId/environment/$environmentId/services/application/$applicationId'
    | '/dashboard/project/$projectId/environment/$environmentId/services/compose/$composeId'
    | '/dashboard/project/$projectId/environment/$environmentId/services/libsql/$libsqlId'
    | '/dashboard/project/$projectId/environment/$environmentId/services/mariadb/$mariadbId'
    | '/dashboard/project/$projectId/environment/$environmentId/services/mongo/$mongoId'
    | '/dashboard/project/$projectId/environment/$environmentId/services/mysql/$mysqlId'
    | '/dashboard/project/$projectId/environment/$environmentId/services/postgres/$postgresId'
    | '/dashboard/project/$projectId/environment/$environmentId/services/redis/$redisId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/invitation'
    | '/register'
    | '/reset-password'
    | '/send-reset-password'
    | '/swagger'
    | '/accept-invitation/$invitationId'
    | '/dashboard/deployments'
    | '/dashboard/docker'
    | '/dashboard/home'
    | '/dashboard/monitoring'
    | '/dashboard/networks'
    | '/dashboard/projects'
    | '/dashboard/requests'
    | '/dashboard/schedules'
    | '/dashboard/swarm'
    | '/dashboard/traefik'
    | '/dashboard/settings/ai'
    | '/dashboard/settings/audit-logs'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/certificates'
    | '/dashboard/settings/cluster'
    | '/dashboard/settings/deployments'
    | '/dashboard/settings/destinations'
    | '/dashboard/settings/git-providers'
    | '/dashboard/settings/invoices'
    | '/dashboard/settings/license'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/registry'
    | '/dashboard/settings/secrets'
    | '/dashboard/settings/server'
    | '/dashboard/settings/servers'
    | '/dashboard/settings/ssh-keys'
    | '/dashboard/settings/sso'
    | '/dashboard/settings/tags'
    | '/dashboard/settings/users'
    | '/dashboard/settings/whitelabeling'
    | '/dashboard/project/$projectId/environment/$environmentId/'
    | '/dashboard/project/$projectId/environment/$environmentId/services/application/$applicationId'
    | '/dashboard/project/$projectId/environment/$environmentId/services/compose/$composeId'
    | '/dashboard/project/$projectId/environment/$environmentId/services/libsql/$libsqlId'
    | '/dashboard/project/$projectId/environment/$environmentId/services/mariadb/$mariadbId'
    | '/dashboard/project/$projectId/environment/$environmentId/services/mongo/$mongoId'
    | '/dashboard/project/$projectId/environment/$environmentId/services/mysql/$mysqlId'
    | '/dashboard/project/$projectId/environment/$environmentId/services/postgres/$postgresId'
    | '/dashboard/project/$projectId/environment/$environmentId/services/redis/$redisId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  InvitationRoute: typeof InvitationRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SendResetPasswordRoute: typeof SendResetPasswordRoute
  SwaggerRoute: typeof SwaggerRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation': {
      id: '/invitation'
      path: '/invitation'
      fullPath: '/invitation'
      preLoaderRoute: typeof InvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-reset-password': {
      id: '/send-reset-password'
      path: '/send-reset-password'
      fullPath: '/send-reset-password'
      preLoaderRoute: typeof SendResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swagger': {
      id: '/swagger'
      path: '/swagger'
      fullPath: '/swagger'
      preLoaderRoute: typeof SwaggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/deployments': {
      id: '/dashboard/deployments'
      path: '/deployments'
      fullPath: '/dashboard/deployments'
      preLoaderRoute: typeof DashboardDeploymentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/docker': {
      id: '/dashboard/docker'
      path: '/docker'
      fullPath: '/dashboard/docker'
      preLoaderRoute: typeof DashboardDockerRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/home': {
      id: '/dashboard/home'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/monitoring': {
      id: '/dashboard/monitoring'
      path: '/monitoring'
      fullPath: '/dashboard/monitoring'
      preLoaderRoute: typeof DashboardMonitoringRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/networks': {
      id: '/dashboard/networks'
      path: '/networks'
      fullPath: '/dashboard/networks'
      preLoaderRoute: typeof DashboardNetworksRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/requests': {
      id: '/dashboard/requests'
      path: '/requests'
      fullPath: '/dashboard/requests'
      preLoaderRoute: typeof DashboardRequestsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/schedules': {
      id: '/dashboard/schedules'
      path: '/schedules'
      fullPath: '/dashboard/schedules'
      preLoaderRoute: typeof DashboardSchedulesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/swarm': {
      id: '/dashboard/swarm'
      path: '/swarm'
      fullPath: '/dashboard/swarm'
      preLoaderRoute: typeof DashboardSwarmRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/traefik': {
      id: '/dashboard/traefik'
      path: '/traefik'
      fullPath: '/dashboard/traefik'
      preLoaderRoute: typeof DashboardTraefikRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/ai': {
      id: '/dashboard/settings/ai'
      path: '/settings/ai'
      fullPath: '/dashboard/settings/ai'
      preLoaderRoute: typeof DashboardSettingsAiRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/audit-logs': {
      id: '/dashboard/settings/audit-logs'
      path: '/settings/audit-logs'
      fullPath: '/dashboard/settings/audit-logs'
      preLoaderRoute: typeof DashboardSettingsAuditLogsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/billing': {
      id: '/dashboard/settings/billing'
      path: '/settings/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof DashboardSettingsBillingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/certificates': {
      id: '/dashboard/settings/certificates'
      path: '/settings/certificates'
      fullPath: '/dashboard/settings/certificates'
      preLoaderRoute: typeof DashboardSettingsCertificatesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/cluster': {
      id: '/dashboard/settings/cluster'
      path: '/settings/cluster'
      fullPath: '/dashboard/settings/cluster'
      preLoaderRoute: typeof DashboardSettingsClusterRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/deployments': {
      id: '/dashboard/settings/deployments'
      path: '/settings/deployments'
      fullPath: '/dashboard/settings/deployments'
      preLoaderRoute: typeof DashboardSettingsDeploymentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/destinations': {
      id: '/dashboard/settings/destinations'
      path: '/settings/destinations'
      fullPath: '/dashboard/settings/destinations'
      preLoaderRoute: typeof DashboardSettingsDestinationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/git-providers': {
      id: '/dashboard/settings/git-providers'
      path: '/settings/git-providers'
      fullPath: '/dashboard/settings/git-providers'
      preLoaderRoute: typeof DashboardSettingsGitProvidersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/invoices': {
      id: '/dashboard/settings/invoices'
      path: '/settings/invoices'
      fullPath: '/dashboard/settings/invoices'
      preLoaderRoute: typeof DashboardSettingsInvoicesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/license': {
      id: '/dashboard/settings/license'
      path: '/settings/license'
      fullPath: '/dashboard/settings/license'
      preLoaderRoute: typeof DashboardSettingsLicenseRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/notifications': {
      id: '/dashboard/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/dashboard/settings/notifications'
      preLoaderRoute: typeof DashboardSettingsNotificationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/profile': {
      id: '/dashboard/settings/profile'
      path: '/settings/profile'
      fullPath: '/dashboard/settings/profile'
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/registry': {
      id: '/dashboard/settings/registry'
      path: '/settings/registry'
      fullPath: '/dashboard/settings/registry'
      preLoaderRoute: typeof DashboardSettingsRegistryRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/secrets': {
      id: '/dashboard/settings/secrets'
      path: '/settings/secrets'
      fullPath: '/dashboard/settings/secrets'
      preLoaderRoute: typeof DashboardSettingsSecretsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/server': {
      id: '/dashboard/settings/server'
      path: '/settings/server'
      fullPath: '/dashboard/settings/server'
      preLoaderRoute: typeof DashboardSettingsServerRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/servers': {
      id: '/dashboard/settings/servers'
      path: '/settings/servers'
      fullPath: '/dashboard/settings/servers'
      preLoaderRoute: typeof DashboardSettingsServersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/ssh-keys': {
      id: '/dashboard/settings/ssh-keys'
      path: '/settings/ssh-keys'
      fullPath: '/dashboard/settings/ssh-keys'
      preLoaderRoute: typeof DashboardSettingsSshKeysRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/sso': {
      id: '/dashboard/settings/sso'
      path: '/settings/sso'
      fullPath: '/dashboard/settings/sso'
      preLoaderRoute: typeof DashboardSettingsSsoRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/tags': {
      id: '/dashboard/settings/tags'
      path: '/settings/tags'
      fullPath: '/dashboard/settings/tags'
      preLoaderRoute: typeof DashboardSettingsTagsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/users': {
      id: '/dashboard/settings/users'
      path: '/settings/users'
      fullPath: '/dashboard/settings/users'
      preLoaderRoute: typeof DashboardSettingsUsersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/whitelabeling': {
      id: '/dashboard/settings/whitelabeling'
      path: '/settings/whitelabeling'
      fullPath: '/dashboard/settings/whitelabeling'
      preLoaderRoute: typeof DashboardSettingsWhitelabelingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/project/$projectId/environment/$environmentId/': {
      id: '/dashboard/project/$projectId/environment/$environmentId/'
      path: '/project/$projectId/environment/$environmentId'
      fullPath: '/dashboard/project/$projectId/environment/$environmentId/'
      preLoaderRoute: typeof DashboardProjectProjectIdEnvironmentEnvironmentIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/project/$projectId/environment/$environmentId/services/application/$applicationId': {
      id: '/dashboard/project/$projectId/environment/$environmentId/services/application/$applicationId'
      path: '/project/$projectId/environment/$environmentId/services/application/$applicationId'
      fullPath: '/dashboard/project/$projectId/environment/$environmentId/services/application/$applicationId'
      preLoaderRoute: typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesApplicationApplicationIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/project/$projectId/environment/$environmentId/services/compose/$composeId': {
      id: '/dashboard/project/$projectId/environment/$environmentId/services/compose/$composeId'
      path: '/project/$projectId/environment/$environmentId/services/compose/$composeId'
      fullPath: '/dashboard/project/$projectId/environment/$environmentId/services/compose/$composeId'
      preLoaderRoute: typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesComposeComposeIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/project/$projectId/environment/$environmentId/services/libsql/$libsqlId': {
      id: '/dashboard/project/$projectId/environment/$environmentId/services/libsql/$libsqlId'
      path: '/project/$projectId/environment/$environmentId/services/libsql/$libsqlId'
      fullPath: '/dashboard/project/$projectId/environment/$environmentId/services/libsql/$libsqlId'
      preLoaderRoute: typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesLibsqlLibsqlIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/project/$projectId/environment/$environmentId/services/mariadb/$mariadbId': {
      id: '/dashboard/project/$projectId/environment/$environmentId/services/mariadb/$mariadbId'
      path: '/project/$projectId/environment/$environmentId/services/mariadb/$mariadbId'
      fullPath: '/dashboard/project/$projectId/environment/$environmentId/services/mariadb/$mariadbId'
      preLoaderRoute: typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMariadbMariadbIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/project/$projectId/environment/$environmentId/services/mongo/$mongoId': {
      id: '/dashboard/project/$projectId/environment/$environmentId/services/mongo/$mongoId'
      path: '/project/$projectId/environment/$environmentId/services/mongo/$mongoId'
      fullPath: '/dashboard/project/$projectId/environment/$environmentId/services/mongo/$mongoId'
      preLoaderRoute: typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMongoMongoIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/project/$projectId/environment/$environmentId/services/mysql/$mysqlId': {
      id: '/dashboard/project/$projectId/environment/$environmentId/services/mysql/$mysqlId'
      path: '/project/$projectId/environment/$environmentId/services/mysql/$mysqlId'
      fullPath: '/dashboard/project/$projectId/environment/$environmentId/services/mysql/$mysqlId'
      preLoaderRoute: typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMysqlMysqlIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/project/$projectId/environment/$environmentId/services/postgres/$postgresId': {
      id: '/dashboard/project/$projectId/environment/$environmentId/services/postgres/$postgresId'
      path: '/project/$projectId/environment/$environmentId/services/postgres/$postgresId'
      fullPath: '/dashboard/project/$projectId/environment/$environmentId/services/postgres/$postgresId'
      preLoaderRoute: typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesPostgresPostgresIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/project/$projectId/environment/$environmentId/services/redis/$redisId': {
      id: '/dashboard/project/$projectId/environment/$environmentId/services/redis/$redisId'
      path: '/project/$projectId/environment/$environmentId/services/redis/$redisId'
      fullPath: '/dashboard/project/$projectId/environment/$environmentId/services/redis/$redisId'
      preLoaderRoute: typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesRedisRedisIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardDeploymentsRoute: typeof DashboardDeploymentsRoute
  DashboardDockerRoute: typeof DashboardDockerRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardMonitoringRoute: typeof DashboardMonitoringRoute
  DashboardNetworksRoute: typeof DashboardNetworksRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardRequestsRoute: typeof DashboardRequestsRoute
  DashboardSchedulesRoute: typeof DashboardSchedulesRoute
  DashboardSwarmRoute: typeof DashboardSwarmRoute
  DashboardTraefikRoute: typeof DashboardTraefikRoute
  DashboardSettingsAiRoute: typeof DashboardSettingsAiRoute
  DashboardSettingsAuditLogsRoute: typeof DashboardSettingsAuditLogsRoute
  DashboardSettingsBillingRoute: typeof DashboardSettingsBillingRoute
  DashboardSettingsCertificatesRoute: typeof DashboardSettingsCertificatesRoute
  DashboardSettingsClusterRoute: typeof DashboardSettingsClusterRoute
  DashboardSettingsDeploymentsRoute: typeof DashboardSettingsDeploymentsRoute
  DashboardSettingsDestinationsRoute: typeof DashboardSettingsDestinationsRoute
  DashboardSettingsGitProvidersRoute: typeof DashboardSettingsGitProvidersRoute
  DashboardSettingsInvoicesRoute: typeof DashboardSettingsInvoicesRoute
  DashboardSettingsLicenseRoute: typeof DashboardSettingsLicenseRoute
  DashboardSettingsNotificationsRoute: typeof DashboardSettingsNotificationsRoute
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute
  DashboardSettingsRegistryRoute: typeof DashboardSettingsRegistryRoute
  DashboardSettingsSecretsRoute: typeof DashboardSettingsSecretsRoute
  DashboardSettingsServerRoute: typeof DashboardSettingsServerRoute
  DashboardSettingsServersRoute: typeof DashboardSettingsServersRoute
  DashboardSettingsSshKeysRoute: typeof DashboardSettingsSshKeysRoute
  DashboardSettingsSsoRoute: typeof DashboardSettingsSsoRoute
  DashboardSettingsTagsRoute: typeof DashboardSettingsTagsRoute
  DashboardSettingsUsersRoute: typeof DashboardSettingsUsersRoute
  DashboardSettingsWhitelabelingRoute: typeof DashboardSettingsWhitelabelingRoute
  DashboardProjectProjectIdEnvironmentEnvironmentIdIndexRoute: typeof DashboardProjectProjectIdEnvironmentEnvironmentIdIndexRoute
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesApplicationApplicationIdRoute: typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesApplicationApplicationIdRoute
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesComposeComposeIdRoute: typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesComposeComposeIdRoute
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesLibsqlLibsqlIdRoute: typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesLibsqlLibsqlIdRoute
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMariadbMariadbIdRoute: typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMariadbMariadbIdRoute
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMongoMongoIdRoute: typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMongoMongoIdRoute
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMysqlMysqlIdRoute: typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMysqlMysqlIdRoute
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesPostgresPostgresIdRoute: typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesPostgresPostgresIdRoute
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesRedisRedisIdRoute: typeof DashboardProjectProjectIdEnvironmentEnvironmentIdServicesRedisRedisIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDeploymentsRoute: DashboardDeploymentsRoute,
  DashboardDockerRoute: DashboardDockerRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardMonitoringRoute: DashboardMonitoringRoute,
  DashboardNetworksRoute: DashboardNetworksRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardRequestsRoute: DashboardRequestsRoute,
  DashboardSchedulesRoute: DashboardSchedulesRoute,
  DashboardSwarmRoute: DashboardSwarmRoute,
  DashboardTraefikRoute: DashboardTraefikRoute,
  DashboardSettingsAiRoute: DashboardSettingsAiRoute,
  DashboardSettingsAuditLogsRoute: DashboardSettingsAuditLogsRoute,
  DashboardSettingsBillingRoute: DashboardSettingsBillingRoute,
  DashboardSettingsCertificatesRoute: DashboardSettingsCertificatesRoute,
  DashboardSettingsClusterRoute: DashboardSettingsClusterRoute,
  DashboardSettingsDeploymentsRoute: DashboardSettingsDeploymentsRoute,
  DashboardSettingsDestinationsRoute: DashboardSettingsDestinationsRoute,
  DashboardSettingsGitProvidersRoute: DashboardSettingsGitProvidersRoute,
  DashboardSettingsInvoicesRoute: DashboardSettingsInvoicesRoute,
  DashboardSettingsLicenseRoute: DashboardSettingsLicenseRoute,
  DashboardSettingsNotificationsRoute: DashboardSettingsNotificationsRoute,
  DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
  DashboardSettingsRegistryRoute: DashboardSettingsRegistryRoute,
  DashboardSettingsSecretsRoute: DashboardSettingsSecretsRoute,
  DashboardSettingsServerRoute: DashboardSettingsServerRoute,
  DashboardSettingsServersRoute: DashboardSettingsServersRoute,
  DashboardSettingsSshKeysRoute: DashboardSettingsSshKeysRoute,
  DashboardSettingsSsoRoute: DashboardSettingsSsoRoute,
  DashboardSettingsTagsRoute: DashboardSettingsTagsRoute,
  DashboardSettingsUsersRoute: DashboardSettingsUsersRoute,
  DashboardSettingsWhitelabelingRoute: DashboardSettingsWhitelabelingRoute,
  DashboardProjectProjectIdEnvironmentEnvironmentIdIndexRoute:
    DashboardProjectProjectIdEnvironmentEnvironmentIdIndexRoute,
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesApplicationApplicationIdRoute:
    DashboardProjectProjectIdEnvironmentEnvironmentIdServicesApplicationApplicationIdRoute,
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesComposeComposeIdRoute:
    DashboardProjectProjectIdEnvironmentEnvironmentIdServicesComposeComposeIdRoute,
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesLibsqlLibsqlIdRoute:
    DashboardProjectProjectIdEnvironmentEnvironmentIdServicesLibsqlLibsqlIdRoute,
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMariadbMariadbIdRoute:
    DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMariadbMariadbIdRoute,
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMongoMongoIdRoute:
    DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMongoMongoIdRoute,
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMysqlMysqlIdRoute:
    DashboardProjectProjectIdEnvironmentEnvironmentIdServicesMysqlMysqlIdRoute,
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesPostgresPostgresIdRoute:
    DashboardProjectProjectIdEnvironmentEnvironmentIdServicesPostgresPostgresIdRoute,
  DashboardProjectProjectIdEnvironmentEnvironmentIdServicesRedisRedisIdRoute:
    DashboardProjectProjectIdEnvironmentEnvironmentIdServicesRedisRedisIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  InvitationRoute: InvitationRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SendResetPasswordRoute: SendResetPasswordRoute,
  SwaggerRoute: SwaggerRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
