/* Autogenerated file. Do not edit manually. */

interface Locales {
	/**
	 * Dokploy
	 */
	'PAGE.register.Dokploy': string;
	/**
	 * Setup the server
	 */
	'PAGE.register.setupServer': string;
	/**
	 * Enter your email and password to setup the server
	 */
	'PAGE.register.enterEmailPassword': string;
	/**
	 * Email
	 */
	'PAGE.register.emailLabel': string;
	/**
	 * email@dokploy.com
	 */
	'PAGE.register.emailPlaceholder': string;
	/**
	 * Password
	 */
	'PAGE.register.passwordLabel': string;
	/**
	 * Password
	 */
	'PAGE.register.passwordPlaceholder': string;
	/**
	 * Confirm Password
	 */
	'PAGE.register.confirmPasswordLabel': string;
	/**
	 * Password
	 */
	'PAGE.register.confirmPasswordPlaceholder': string;
	/**
	 * Register
	 */
	'PAGE.register.registerButton': string;
	/**
	 * Already have account?
	 */
	'PAGE.register.alreadyHaveAccount': string;
	/**
	 * Sign in
	 */
	'PAGE.register.signInLink': string;
	/**
	 * Need help?
	 */
	'PAGE.register.needHelp': string;
	/**
	 * Contact us
	 */
	'PAGE.register.contactUsLink': string;
	/**
	 * Email is required
	 */
	'PAGE.login.email.required': string;
	/**
	 * Email must be a valid email
	 */
	'PAGE.login.email.invalid': string;
	/**
	 * Password is required
	 */
	'PAGE.login.password.required': string;
	/**
	 * Password must be at least 8 characters
	 */
	'PAGE.login.password.minLength': string;
	/**
	 * Signin successfully
	 */
	'PAGE.login.success': string;
	/**
	 * Signin failed
	 */
	'PAGE.login.failure': string;
	/**
	 * Dokploy
	 */
	'PAGE.login.Dokploy': string;
	/**
	 * Sign in
	 */
	'PAGE.login.signIn': string;
	/**
	 * Enter your credentials to access your account
	 */
	'PAGE.login.enterCredentials': string;
	/**
	 * Email
	 */
	'PAGE.login.emailLabel': string;
	/**
	 * Email
	 */
	'PAGE.login.emailPlaceholder': string;
	/**
	 * Password
	 */
	'PAGE.login.passwordLabel': string;
	/**
	 * Password
	 */
	'PAGE.login.passwordPlaceholder': string;
	/**
	 * Login
	 */
	'PAGE.login.loginButton': string;
	/**
	 * Don't have an account?
	 */
	'PAGE.login.dontHaveAccount': string;
	/**
	 * Sign up
	 */
	'PAGE.login.signUpLink': string;
	/**
	 * Need help?
	 */
	'PAGE.login.needHelp': string;
	/**
	 * Contact us
	 */
	'PAGE.login.contactUsLink': string;
	/**
	 * Lost your password?
	 */
	'PAGE.login.lostPasswordLink': string;
	/**
	 * Projects
	 */
	'PAGE.project.projects': string;
	/**
	 * Create Service
	 */
	'PAGE.project.createService': string;
	/**
	 * No services added yet. Click on Create Service.
	 */
	'PAGE.project.noServicesAdded': string;
	/**
	 * Created
	 */
	'PAGE.project.created': string;
	/**
	 * Actions
	 */
	'PAGE.project.actions': string;
	/**
	 * Projects
	 */
	'NAVIGATION.tabs.projects.label': string;
	/**
	 * Manage your projects
	 */
	'NAVIGATION.tabs.projects.description': string;
	/**
	 * Monitoring
	 */
	'NAVIGATION.tabs.monitoring.label': string;
	/**
	 * Monitor your projects
	 */
	'NAVIGATION.tabs.monitoring.description': string;
	/**
	 * Traefik
	 */
	'NAVIGATION.tabs.traefik.label': string;
	/**
	 * Traefik File System
	 */
	'NAVIGATION.tabs.traefik.tabLabel': string;
	/**
	 * Manage your traefik
	 */
	'NAVIGATION.tabs.traefik.description': string;
	/**
	 * Docker
	 */
	'NAVIGATION.tabs.docker.label': string;
	/**
	 * Manage your docker
	 */
	'NAVIGATION.tabs.docker.description': string;
	/**
	 * Settings
	 */
	'NAVIGATION.tabs.settings.label': string;
	/**
	 * Manage your settings
	 */
	'NAVIGATION.tabs.settings.description': string;
}

export default Locales;
