/* Autogenerated file. Do not edit manually. */

interface Locales {
  /**
   * Dokploy
   */
  'PAGE.register.Dokploy': string;
  /**
   * 设置服务器
   */
  'PAGE.register.setupServer': string;
  /**
   * 输入您的电子邮件和密码以设置服务器
   */
  'PAGE.register.enterEmailPassword': string;
  /**
   * 电子邮件
   */
  'PAGE.register.emailLabel': string;
  /**
   * email@dokploy.com
   */
  'PAGE.register.emailPlaceholder': string;
  /**
   * 密码
   */
  'PAGE.register.passwordLabel': string;
  /**
   * 密码
   */
  'PAGE.register.passwordPlaceholder': string;
  /**
   * 确认密码
   */
  'PAGE.register.confirmPasswordLabel': string;
  /**
   * 密码
   */
  'PAGE.register.confirmPasswordPlaceholder': string;
  /**
   * 注册
   */
  'PAGE.register.registerButton': string;
  /**
   * 已有账户？
   */
  'PAGE.register.alreadyHaveAccount': string;
  /**
   * 登录
   */
  'PAGE.register.signInLink': string;
  /**
   * 需要帮助？
   */
  'PAGE.register.needHelp': string;
  /**
   * 联系我们
   */
  'PAGE.register.contactUsLink': string;
  /**
   * 电子邮件是必填项
   */
  'PAGE.login.email.required': string;
  /**
   * 电子邮件必须是有效的电子邮件
   */
  'PAGE.login.email.invalid': string;
  /**
   * 密码是必填项
   */
  'PAGE.login.password.required': string;
  /**
   * 密码必须至少有8个字符
   */
  'PAGE.login.password.minLength': string;
  /**
   * 登录成功
   */
  'PAGE.login.success': string;
  /**
   * 登录失败
   */
  'PAGE.login.failure': string;
  /**
   * Dokploy
   */
  'PAGE.login.Dokploy': string;
  /**
   * 登录
   */
  'PAGE.login.signIn': string;
  /**
   * 输入您的凭据以访问您的账户
   */
  'PAGE.login.enterCredentials': string;
  /**
   * 电子邮件
   */
  'PAGE.login.emailLabel': string;
  /**
   * 电子邮件
   */
  'PAGE.login.emailPlaceholder': string;
  /**
   * 密码
   */
  'PAGE.login.passwordLabel': string;
  /**
   * 密码
   */
  'PAGE.login.passwordPlaceholder': string;
  /**
   * 登录
   */
  'PAGE.login.loginButton': string;
  /**
   * 还没有账户？
   */
  'PAGE.login.dontHaveAccount': string;
  /**
   * 注册
   */
  'PAGE.login.signUpLink': string;
  /**
   * 需要帮助？
   */
  'PAGE.login.needHelp': string;
  /**
   * 联系我们
   */
  'PAGE.login.contactUsLink': string;
  /**
   * 忘记密码？
   */
  'PAGE.login.lostPasswordLink': string;
  /**
   * 项目
   */
  'PAGE.project.projects': string;
  /**
   * 创建服务
   */
  'PAGE.project.createService': string;
  /**
   * 尚未添加任何服务。点击创建服务。
   */
  'PAGE.project.noServicesAdded': string;
  /**
   * 创建时间
   */
  'PAGE.project.created': string;
  /**
   * 操作
   */
  'PAGE.project.actions': string;
  /**
   * 项目
   */
  'NAVIGATION.tabs.projects.label': string;
  /**
   * 管理您的项目
   */
  'NAVIGATION.tabs.projects.description': string;
  /**
   * 监控
   */
  'NAVIGATION.tabs.monitoring.label': string;
  /**
   * 监控您的项目
   */
  'NAVIGATION.tabs.monitoring.description': string;
  /**
   * Traefik
   */
  'NAVIGATION.tabs.traefik.label': string;
  /**
   * Traefik 文件系统
   */
  'NAVIGATION.tabs.traefik.tabLabel': string;
  /**
   * 管理您的 Traefik
   */
  'NAVIGATION.tabs.traefik.description': string;
  /**
   * Docker
   */
  'NAVIGATION.tabs.docker.label': string;
  /**
   * 管理您的 Docker
   */
  'NAVIGATION.tabs.docker.description': string;
  /**
   * 设置
   */
  'NAVIGATION.tabs.settings.label': string;
  /**
   * 管理您的设置
   */
  'NAVIGATION.tabs.settings.description': string;
}

export default Locales;
