/* Autogenerated file. Do not edit manually. */

interface Locales {
	/**
	 * Dokploy
	 */
	'PAGE.register.Dokploy': string;
	/**
	 * Setup the server
	 */
	'PAGE.register.setupServer': string;
	/**
	 * Enter your email and password to setup the server
	 */
	'PAGE.register.enterEmailPassword': string;
	/**
	 * Email
	 */
	'PAGE.register.emailLabel': string;
	/**
	 * email@dokploy.com
	 */
	'PAGE.register.emailPlaceholder': string;
	/**
	 * Password
	 */
	'PAGE.register.passwordLabel': string;
	/**
	 * Password
	 */
	'PAGE.register.passwordPlaceholder': string;
	/**
	 * Confirm Password
	 */
	'PAGE.register.confirmPasswordLabel': string;
	/**
	 * Password
	 */
	'PAGE.register.confirmPasswordPlaceholder': string;
	/**
	 * Register
	 */
	'PAGE.register.registerButton': string;
	/**
	 * Already have account?
	 */
	'PAGE.register.alreadyHaveAccount': string;
	/**
	 * Sign in
	 */
	'PAGE.register.signInLink': string;
	/**
	 * Need help?
	 */
	'PAGE.register.needHelp': string;
	/**
	 * Contact us
	 */
	'PAGE.register.contactUsLink': string;
	/**
	 * Email is required
	 */
	'PAGE.login.email.required': string;
	/**
	 * Email must be a valid email
	 */
	'PAGE.login.email.invalid': string;
	/**
	 * Password is required
	 */
	'PAGE.login.password.required': string;
	/**
	 * Password must be at least 8 characters
	 */
	'PAGE.login.password.minLength': string;
	/**
	 * Signin successfully
	 */
	'PAGE.login.success': string;
	/**
	 * Signin failed
	 */
	'PAGE.login.failure': string;
	/**
	 * Dokploy
	 */
	'PAGE.login.Dokploy': string;
	/**
	 * Sign in
	 */
	'PAGE.login.signIn': string;
	/**
	 * Enter your credentials to access your account
	 */
	'PAGE.login.enterCredentials': string;
	/**
	 * Email
	 */
	'PAGE.login.emailLabel': string;
	/**
	 * Email
	 */
	'PAGE.login.emailPlaceholder': string;
	/**
	 * Password
	 */
	'PAGE.login.passwordLabel': string;
	/**
	 * Password
	 */
	'PAGE.login.passwordPlaceholder': string;
	/**
	 * Login
	 */
	'PAGE.login.loginButton': string;
	/**
	 * Don't have an account?
	 */
	'PAGE.login.dontHaveAccount': string;
	/**
	 * Sign up
	 */
	'PAGE.login.signUpLink': string;
	/**
	 * Need help?
	 */
	'PAGE.login.needHelp': string;
	/**
	 * Contact us
	 */
	'PAGE.login.contactUsLink': string;
	/**
	 * Lost your password?
	 */
	'PAGE.login.lostPasswordLink': string;
	/**
	 * Projects
	 */
	'PAGE.project.projects': string;
	/**
	 * Create Service
	 */
	'PAGE.project.createService': string;
	/**
	 * No services added yet. Click on Create Service.
	 */
	'PAGE.project.noServicesAdded': string;
	/**
	 * Created
	 */
	'PAGE.project.created': string;
	/**
	 * Actions
	 */
	'PAGE.project.actions': string;
	/**
	 * Dokploy
	 */
	'NAVBAR.Dokploy': string;
	/**
	 * Support
	 */
	'NAVBAR.support': string;
	/**
	 * My Account
	 */
	'PAGE.account.myAccount': string;
	/**
	 * Projects
	 */
	'PAGE.account.projects': string;
	/**
	 * Monitoring
	 */
	'PAGE.account.monitoring': string;
	/**
	 * Traefik
	 */
	'PAGE.account.traefik': string;
	/**
	 * Docker
	 */
	'PAGE.account.docker': string;
	/**
	 * Settings
	 */
	'PAGE.account.settings': string;
	/**
	 * Log out
	 */
	'PAGE.account.logout': string;
	/**
	 * Server
	 */
	'PAGE.settings.server': string;
	/**
	 * Profile
	 */
	'PAGE.settings.profile': string;
	/**
	 * Appearance
	 */
	'PAGE.settings.appearance': string;
	/**
	 * S3 Destinations
	 */
	'PAGE.settings.destinations': string;
	/**
	 * Certificates
	 */
	'PAGE.settings.certificates': string;
	/**
	 * SSH Keys
	 */
	'PAGE.settings.sshKeys': string;
	/**
	 * Git
	 */
	'PAGE.settings.git': string;
	/**
	 * Users
	 */
	'PAGE.settings.users': string;
	/**
	 * Cluster
	 */
	'PAGE.settings.cluster': string;
	/**
	 * Notifications
	 */
	'PAGE.settings.notifications': string;
	/**
	 * Server Domain
	 */
	'PAGE.webDomain.title': string;
	/**
	 * Add your server domain to your application
	 */
	'PAGE.webDomain.description': string;
	/**
	 * Domain
	 */
	'PAGE.webDomain.domainLabel': string;
	/**
	 * dokploy.com
	 */
	'PAGE.webDomain.domainPlaceholder': string;
	/**
	 * Letsencrypt Email
	 */
	'PAGE.webDomain.letsEncryptEmailLabel': string;
	/**
	 * Dp4kz@example.com
	 */
	'PAGE.webDomain.letsEncryptEmailPlaceholder': string;
	/**
	 * Certificate
	 */
	'PAGE.webDomain.certificateLabel': string;
	/**
	 * Select a certificate
	 */
	'PAGE.webDomain.certificateSelectPlaceholder': string;
	/**
	 * None
	 */
	'PAGE.webDomain.certificateNone': string;
	/**
	 * Letsencrypt (Default)
	 */
	'PAGE.webDomain.certificateLetsEncrypt': string;
	/**
	 * Save
	 */
	'PAGE.webDomain.saveButton': string;
	/**
	 * URL is required
	 */
	'PAGE.webDomain.domainRequired': string;
	/**
	 * Email is required
	 */
	'PAGE.webDomain.emailRequired': string;
	/**
	 * Domain Assigned
	 */
	'PAGE.webDomain.toastSuccess': string;
	/**
	 * Error to assign the domain
	 */
	'PAGE.webDomain.toastError': string;
	/**
	 * Web server settings
	 */
	'PAGE.webServerSettings.title': string;
	/**
	 * Reload or clean the web server.
	 */
	'PAGE.webServerSettings.description': string;
	/**
	 * Server
	 */
	'PAGE.webServerSettings.serverButton': string;
	/**
	 * Actions
	 */
	'PAGE.webServerSettings.actions': string;
	/**
	 * Reload
	 */
	'PAGE.webServerSettings.reloadServer': string;
	/**
	 * Watch logs
	 */
	'PAGE.webServerSettings.watchLogs': string;
	/**
	 * View Traefik config
	 */
	'PAGE.webServerSettings.viewTraefikConfig': string;
	/**
	 * View middlewares config
	 */
	'PAGE.webServerSettings.viewMiddlewaresConfig': string;
	/**
	 * Enter the terminal
	 */
	'PAGE.webServerSettings.enterTerminal': string;
	/**
	 * Traefik
	 */
	'PAGE.webServerSettings.traefikButton': string;
	/**
	 * Reload
	 */
	'PAGE.webServerSettings.reloadTraefik': string;
	/**
	 * Modify Env
	 */
	'PAGE.webServerSettings.modifyEnv': string;
	/**
	 * @@enable@@ Dashboard
	 */
	'PAGE.webServerSettings.dashboard': string;
	/**
	 * Enable
	 */
	'PAGE.webServerSettings.enableDashboard': string;
	/**
	 * Disabled
	 */
	'PAGE.webServerSettings.disableDashboard': string;
	/**
	 * Space
	 */
	'PAGE.webServerSettings.spaceButton': string;
	/**
	 * Clean unused images
	 */
	'PAGE.webServerSettings.cleanUnusedImages': string;
	/**
	 * Clean unused volumes
	 */
	'PAGE.webServerSettings.cleanUnusedVolumes': string;
	/**
	 * Clean stopped containers
	 */
	'PAGE.webServerSettings.cleanStoppedContainers': string;
	/**
	 * Clean Docker Builder & System
	 */
	'PAGE.webServerSettings.cleanDockerBuilder': string;
	/**
	 * Clean Monitoring
	 */
	'PAGE.webServerSettings.cleanMonitoring': string;
	/**
	 * Clean all
	 */
	'PAGE.webServerSettings.cleanAll': string;
	/**
	 * Server IP: @@serverIp@@
	 */
	'PAGE.webServerSettings.serverIp': string;
	/**
	 * Version: @@dokployVersion@@
	 */
	'PAGE.webServerSettings.version': string;
	/**
	 * Daily Docker Cleanup
	 */
	'PAGE.webServerSettings.dailyDockerCleanup': string;
	/**
	 * Docker Cleanup Enabled
	 */
	'PAGE.webServerSettings.dockerCleanupEnabled': string;
	/**
	 * Docker Cleanup Error
	 */
	'PAGE.webServerSettings.dockerCleanupError': string;
	/**
	 * Server Reloaded
	 */
	'PAGE.webServerSettings.serverReloadedSuccess': string;
	/**
	 * Error reloading the server
	 */
	'PAGE.webServerSettings.serverReloadedError': string;
	/**
	 * Traefik Reloaded
	 */
	'PAGE.webServerSettings.traefikReloadedSuccess': string;
	/**
	 * Error to reload the traefik
	 */
	'PAGE.webServerSettings.traefikReloadedError': string;
	/**
	 * Cleaned images
	 */
	'PAGE.webServerSettings.cleanedImagesSuccess': string;
	/**
	 * Error to clean images
	 */
	'PAGE.webServerSettings.cleanedImagesError': string;
	/**
	 * Cleaned volumes
	 */
	'PAGE.webServerSettings.cleanedVolumesSuccess': string;
	/**
	 * Error to clean volumes
	 */
	'PAGE.webServerSettings.cleanedVolumesError': string;
	/**
	 * Stopped containers cleaned
	 */
	'PAGE.webServerSettings.cleanedStoppedContainersSuccess': string;
	/**
	 * Error to clean stopped containers
	 */
	'PAGE.webServerSettings.cleanedStoppedContainersError': string;
	/**
	 * Cleaned Docker Builder
	 */
	'PAGE.webServerSettings.cleanedDockerBuilderSuccess': string;
	/**
	 * Error to clean Docker Builder
	 */
	'PAGE.webServerSettings.cleanedDockerBuilderError': string;
	/**
	 * Cleaned Monitoring
	 */
	'PAGE.webServerSettings.cleanedMonitoringSuccess': string;
	/**
	 * Error to clean Monitoring
	 */
	'PAGE.webServerSettings.cleanedMonitoringError': string;
	/**
	 * Cleaned all
	 */
	'PAGE.webServerSettings.cleanedAllSuccess': string;
	/**
	 * Error to clean all
	 */
	'PAGE.webServerSettings.cleanedAllError': string;
	/**
	 * Enabled @@dashboard@@
	 */
	'PAGE.webServerSettings.dashboardEnabled': string;
	/**
	 * Disabled @@dashboard@@
	 */
	'PAGE.webServerSettings.dashboardDisabled': string;
	/**
	 * Updates
	 */
	'PAGE.webServerSettings.updates': string;
	/**
	 * Web Server Update
	 */
	'PAGE.webServerSettings.webServerUpdate': string;
	/**
	 * Check new releases and update your dokploy
	 */
	'PAGE.webServerSettings.checkNewReleases': string;
	/**
	 * We suggest to update your dokploy to the latest version only if you:
	 */
	'PAGE.webServerSettings.suggestToUpdate': string;
	/**
	 * Want to try the latest features
	 */
	'PAGE.webServerSettings.wantToTryLatestFeatures': string;
	/**
	 * Some bug that is blocking to use some features
	 */
	'PAGE.webServerSettings.bugBlockingFeatures': string;
	/**
	 * Please we recommend to see the latest version to see if there are any breaking changes before updating. Go to
	 */
	'PAGE.webServerSettings.recommendSeeLatestVersion': string;
	/**
	 * Dokploy Releases
	 */
	'PAGE.webServerSettings.dokployReleases': string;
	/**
	 * to check the latest version.
	 */
	'PAGE.webServerSettings.checkLatestVersion': string;
	/**
	 * You are using the latest version
	 */
	'PAGE.webServerSettings.usingLatestVersion': string;
	/**
	 * Check updates
	 */
	'PAGE.webServerSettings.checkUpdates': string;
	/**
	 * Error to check updates
	 */
	'PAGE.webServerSettings.errorToCheckUpdates': string;
	/**
	 * Check updates
	 */
	'PAGE.webServerSettings.successCheckUpdates': string;
	/**
	 * Monitoring
	 */
	'PAGE.dockerMonitoring.title': string;
	/**
	 * Watch the usage of your server in the current app
	 */
	'PAGE.dockerMonitoring.description': string;
	/**
	 * CPU
	 */
	'PAGE.dockerMonitoring.cpu': string;
	/**
	 * Used: @@value@@%
	 */
	'PAGE.dockerMonitoring.cpuUsed': string;
	/**
	 * Memory
	 */
	'PAGE.dockerMonitoring.memory': string;
	/**
	 * Used: @@used@@ GB / Limit: @@limit@@ GB
	 */
	'PAGE.dockerMonitoring.memoryUsed': string;
	/**
	 * Space
	 */
	'PAGE.dockerMonitoring.space': string;
	/**
	 * Used: @@used@@ GB / Limit: @@limit@@ GB
	 */
	'PAGE.dockerMonitoring.spaceUsed': string;
	/**
	 * Block I/O
	 */
	'PAGE.dockerMonitoring.blockIO': string;
	/**
	 * Used: @@read@@ MB / Limit: @@write@@ MB
	 */
	'PAGE.dockerMonitoring.blockIOUsed': string;
	/**
	 * Network
	 */
	'PAGE.dockerMonitoring.network': string;
	/**
	 * In MB: @@input@@ MB / Out MB: @@output@@ MB
	 */
	'PAGE.dockerMonitoring.networkInOut': string;
	/**
	 * Name
	 */
	'FORM.addProject.name': string;
	/**
	 * Description
	 */
	'FORM.addProject.description': string;
	/**
	 * Create Project
	 */
	'FORM.addProject.createProject': string;
	/**
	 * Add a project
	 */
	'FORM.addProject.addAProject': string;
	/**
	 * The home of something big!
	 */
	'FORM.addProject.homeOfSomethingBig': string;
	/**
	 * Tesla
	 */
	'FORM.addProject.placeholderName': string;
	/**
	 * Description about your project...
	 */
	'FORM.addProject.placeholderDescription': string;
	/**
	 * Create
	 */
	'FORM.addProject.create': string;
	/**
	 * Project Created
	 */
	'FORM.addProject.projectCreated': string;
	/**
	 * Error to create a project
	 */
	'FORM.addProject.errorCreatingProject': string;
	/**
	 * Name is required
	 */
	'FORM.addProject.nameIsRequired': string;
	/**
	 * Projects
	 */
	'NAVIGATION.tabs.projects.label': string;
	/**
	 * Manage your projects
	 */
	'NAVIGATION.tabs.projects.description': string;
	/**
	 * Monitoring
	 */
	'NAVIGATION.tabs.monitoring.label': string;
	/**
	 * Monitor your projects
	 */
	'NAVIGATION.tabs.monitoring.description': string;
	/**
	 * Traefik
	 */
	'NAVIGATION.tabs.traefik.label': string;
	/**
	 * Traefik File System
	 */
	'NAVIGATION.tabs.traefik.tabLabel': string;
	/**
	 * Manage your traefik
	 */
	'NAVIGATION.tabs.traefik.description': string;
	/**
	 * Docker
	 */
	'NAVIGATION.tabs.docker.label': string;
	/**
	 * Manage your docker
	 */
	'NAVIGATION.tabs.docker.description': string;
	/**
	 * Settings
	 */
	'NAVIGATION.tabs.settings.label': string;
	/**
	 * Manage your settings
	 */
	'NAVIGATION.tabs.settings.description': string;
	/**
	 * Requests
	 */
	'NAVIGATION.tabs.requests.label': string;
	/**
	 * Manage your requests
	 */
	'NAVIGATION.tabs.requests.description': string;
}

export default Locales;
