version: '3.8'

services:
  dokploy-postgres:
    image: postgres:16-alpine
    container_name: dokploy-postgres-dev
    environment:
      POSTGRES_USER: dokploy
      POSTGRES_PASSWORD: amukds4wi9001583845717ad2
      POSTGRES_DB: dokploy
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
