services:
  postgres:
    image: postgres:18
    container_name: dokploy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dokploy
      POSTGRES_PASSWORD: a9962c44a95ddc5b7dc804b656b96137dec2ef0abeb77e40
      POSTGRES_DB: dokploy
      PGDATA: /var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - dokploy-postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dokploy -d dokploy"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  dokploy-postgres:
