packages:
  - apps/api
  - apps/dokploy
  - apps/schedules
  - packages/server

onlyBuiltDependencies:
  - '@scarf/scarf'
  - '@tree-sitter-grammars/tree-sitter-yaml'
  - bcrypt
  - core-js
  - core-js-pure
  - cpu-features
  - esbuild
  - lefthook
  - msgpackr-extract
  - node-pty
  - protobufjs
  - sharp
  - ssh2
  - tree-sitter
  - tree-sitter-json
