import { parse } from "yaml";
import { getBuiltImageTag } from "./compose-remote-build";

/**
 * Pure helpers for pruning old `dpl-<deploymentId>` tags from a compose build
 * registry. Nothing here touches the network, the database or a shell: it
 * decides *what* may be deleted and builds the (secret-free) commands and the
 * stdin payloads that do the talking. The orchestration, including which host
 * runs what, lives in `services/compose-registry-retention.ts`.
 *
 * Registry model (registry:2 / distribution v2 API):
 *
 * - a manifest is deleted by *digest*, and that removes every tag pointing at
 *   it. `latest` and the newest `dpl-` tag share a digest, and a service that did
 *   not change between deploys keeps the same digest under several `dpl-` tags,
 *   so a tag can only be dropped when no tag we keep resolves to its digest;
 * - tags themselves cannot be deleted, only manifests, and blobs are only
 *   reclaimed by `registry garbage-collect`, which is out of scope here.
 */

/** Prefix of every tag the build-server flow pushes per deployment. */
export const DPL_TAG_PREFIX = "dpl-";

/** The newest `dpl-` tags kept per service repository. */
export const BUILD_REGISTRY_KEEP_DPL_TAGS = 5;

/** `Accept` value that makes the registry return the manifest as stored. */
export const MANIFEST_ACCEPT = [
	"application/vnd.docker.distribution.manifest.v2+json",
	"application/vnd.docker.distribution.manifest.list.v2+json",
	"application/vnd.oci.image.manifest.v1+json",
	"application/vnd.oci.image.index.v1+json",
].join(", ");

const REPO_PATTERN = /^[a-z0-9][a-z0-9._/-]*$/;
const TAG_PATTERN = /^[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$/;
const DIGEST_PATTERN = /^sha256:[a-f0-9]{64}$/;

export const isValidRepoName = (repo: string) =>
	REPO_PATTERN.test(repo) && !repo.includes("..") && !repo.includes("//");
export const isValidTag = (tag: string) => TAG_PATTERN.test(tag);
export const isValidDigest = (digest: string) => DIGEST_PATTERN.test(digest);
export const isDplTag = (tag: string) => tag.startsWith(DPL_TAG_PREFIX);

export interface RegistryImageRef {
	host: string;
	repo: string;
	tag: string;
}

/** Splits `host[:port]/path/to/repo:tag`. `null` for anything else (digest refs, bare names). */
export const parseRegistryImageRef = (ref: string): RegistryImageRef | null => {
	const value = ref.trim();
	if (!value || value.includes("@")) return null;
	const slash = value.indexOf("/");
	if (slash <= 0) return null;
	const host = value.slice(0, slash).toLowerCase();
	const rest = value.slice(slash + 1);
	const colon = rest.lastIndexOf(":");
	if (colon <= 0 || colon < rest.lastIndexOf("/")) return null;
	const repo = rest.slice(0, colon);
	const tag = rest.slice(colon + 1);
	if (!isValidRepoName(repo) || !isValidTag(tag)) return null;
	return { host, repo, tag };
};

export interface RegistryEndpoint {
	/** `host[:port]`, lowercase, no scheme. */
	host: string;
	/** A scheme the user typed explicitly. */
	scheme: "http" | "https" | null;
}

export const parseRegistryEndpoint = (
	registryUrl: string | null | undefined,
): RegistryEndpoint | null => {
	const value = (registryUrl ?? "").trim();
	if (!value) return null;
	const scheme = /^(https?):\/\//i.exec(value)?.[1]?.toLowerCase() as
		| "http"
		| "https"
		| undefined;
	const host = value
		.replace(/^https?:\/\//i, "")
		.replace(/\/.*$/, "")
		.toLowerCase();
	// `@` would turn what precedes it into userinfo and move the real host.
	if (!host || /[\s"'\\@]/.test(host)) return null;
	return { host, scheme: scheme ?? null };
};

export const isLoopbackHost = (host: string) => {
	const bare = host.startsWith("[")
		? host.slice(1, host.indexOf("]"))
		: host.replace(/:\d+$/, "");
	return bare === "localhost" || bare === "::1" || /^127(\.\d+){3}$/.test(bare);
};

/**
 * Base URLs to try, in order. The credentials only ever go over plain http to
 * a loopback address (the SSH-tunnelled registry) or when the user typed
 * `http://` themselves; everything else is https-only.
 */
export const getRegistryApiBases = (endpoint: RegistryEndpoint): string[] => {
	if (endpoint.scheme) return [`${endpoint.scheme}://${endpoint.host}`];
	if (isLoopbackHost(endpoint.host)) {
		return [`http://${endpoint.host}`, `https://${endpoint.host}`];
	}
	return [`https://${endpoint.host}`];
};

/**
 * Every image reference a compose build override (or one of its backups) pins.
 * The file is generated by `buildComposeOverrideYaml`; anything unparsable
 * yields no references.
 */
export const parseOverrideImages = (yaml: string): string[] => {
	let parsed: unknown;
	try {
		parsed = parse(yaml);
	} catch {
		return [];
	}
	const services = (parsed as { services?: Record<string, unknown> } | null)
		?.services;
	if (!services || typeof services !== "object") return [];
	const images: string[] = [];
	for (const definition of Object.values(services)) {
		const image = (definition as { image?: unknown } | null)?.image;
		if (typeof image === "string" && image.trim()) images.push(image.trim());
	}
	return images;
};

/** Marker the file-reading command prints in front of each file. */
export const OVERRIDE_FILE_MARKER = "@@DPL-FILE";

/**
 * Prints the given files, each behind a marker line, tolerating missing ones.
 * Paths must already be shell-quoted.
 */
export const getReadFilesCommand = (quotedPaths: string[]) =>
	`for f in ${quotedPaths.join(" ")}; do echo "${OVERRIDE_FILE_MARKER} $f"; cat "$f" 2>/dev/null; echo; done; true`;

/** Splits the output of `getReadFilesCommand` into one text per file. */
export const splitFileOutput = (stdout: string): string[] =>
	stdout
		.split(new RegExp(`^${OVERRIDE_FILE_MARKER} .*$`, "m"))
		.slice(1)
		.map((part) => part.trim());

/** tag -> deployment `createdAt` (ms) for the deployments we still have rows for. */
export const mapDeploymentTagTimes = (
	deployments: { deploymentId: string; createdAt: string }[],
) => {
	const times = new Map<string, number>();
	for (const { deploymentId, createdAt } of deployments) {
		const time = Date.parse(createdAt);
		if (!Number.isNaN(time)) times.set(getBuiltImageTag(deploymentId), time);
	}
	return times;
};

export interface RepoTagPlan {
	/** `dpl-` tags that nothing needs; candidates for deletion, oldest first. */
	doomedTags: string[];
	/** Every other tag in the repository. */
	keptTags: string[];
}

/**
 * Splits a repository's tags into keep and doom.
 *
 * Kept, always: every tag that is not a `dpl-` tag (`latest`, anything a human
 * pushed), every tag in `protectedTags` (what the current release and the
 * rollback snapshots reference), and the `keep` newest `dpl-` tags. "Newest"
 * is the creation time of the deployment that pushed the tag, never the tag
 * text (deployment ids are random). A tag whose deployment row is gone (the
 * table only keeps the last ten per compose) ranks older than every known one.
 */
export const planRepoTags = ({
	tags,
	protectedTags,
	tagTimes,
	keep = BUILD_REGISTRY_KEEP_DPL_TAGS,
}: {
	tags: string[];
	protectedTags: ReadonlySet<string>;
	tagTimes: ReadonlyMap<string, number>;
	keep?: number;
}): RepoTagPlan => {
	const unique = [...new Set(tags)];
	const dpl = unique.filter(isDplTag);
	const newestFirst = [...dpl].sort((a, b) => {
		const timeA = tagTimes.get(a);
		const timeB = tagTimes.get(b);
		if (timeA !== undefined && timeB !== undefined && timeA !== timeB) {
			return timeB - timeA;
		}
		if (timeA === undefined && timeB !== undefined) return 1;
		if (timeA !== undefined && timeB === undefined) return -1;
		return b < a ? -1 : b > a ? 1 : 0;
	});
	const newest = new Set(newestFirst.slice(0, Math.max(0, keep)));
	const doomedTags = newestFirst
		.filter((tag) => !newest.has(tag) && !protectedTags.has(tag))
		.reverse();
	const doomed = new Set(doomedTags);
	return {
		doomedTags,
		keptTags: unique.filter((tag) => !doomed.has(tag)),
	};
};

/**
 * The digests that may be deleted: those of doomed tags that no kept tag
 * resolves to, directly or as a child of a kept manifest list. A doomed tag
 * whose digest could not be read is simply left alone.
 */
export const selectDigestsToDelete = ({
	doomedDigests,
	protectedDigests,
}: {
	doomedDigests: ReadonlyMap<string, string>;
	protectedDigests: ReadonlySet<string>;
}) => {
	const deleteDigests: string[] = [];
	const deleteTags: string[] = [];
	const heldBack: { tag: string; digest: string }[] = [];
	for (const [tag, digest] of doomedDigests) {
		if (protectedDigests.has(digest)) {
			heldBack.push({ tag, digest });
			continue;
		}
		deleteTags.push(tag);
		if (!deleteDigests.includes(digest)) deleteDigests.push(digest);
	}
	return { deleteDigests, deleteTags, heldBack };
};

/** Child manifest digests of an index / manifest list; `[]` for a plain manifest. */
export const getManifestChildDigests = (body: string): string[] => {
	try {
		const parsed = JSON.parse(body) as {
			manifests?: { digest?: unknown }[];
		};
		if (!Array.isArray(parsed.manifests)) return [];
		return parsed.manifests
			.map((entry) => entry?.digest)
			.filter(
				(digest): digest is string =>
					typeof digest === "string" && isValidDigest(digest),
			);
	} catch {
		return [];
	}
};

// ---------------------------------------------------------------------------
// HTTP through curl on the build server
// ---------------------------------------------------------------------------

export interface RegistryRequest {
	/** Echoed back in the output so responses can be matched to requests. */
	id: number;
	method: "GET" | "HEAD" | "DELETE";
	url: string;
	/** Send the manifest `Accept` header. */
	manifest?: boolean;
	/** Print the response headers in front of the body (GET). */
	includeHeaders?: boolean;
}

/** Marker curl prints after each response (`-w`). */
const RESPONSE_MARKER = "@@DPL";

/**
 * Escapes a value for a double-quoted string in a curl config file. Line breaks
 * cannot be represented in a header or a credential, so they are rejected.
 */
export const curlConfigQuote = (value: string) => {
	if (/[\r\n\0]/.test(value)) {
		throw new Error("Value cannot be written to a curl config file");
	}
	return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
};

/**
 * The curl config fed to `curl --config -` on stdin. This is the only place
 * the registry password appears: it never reaches a command line, the
 * environment, a file or a log.
 */
export const buildRegistryCurlConfig = ({
	requests,
	username,
	password,
	timeoutSeconds = 20,
}: {
	requests: RegistryRequest[];
	username?: string | null;
	password?: string | null;
	timeoutSeconds?: number;
}) => {
	const blocks = requests.map((request) => {
		const lines = [
			`url = ${curlConfigQuote(request.url)}`,
			"silent",
			// No URL globbing: `[` `]` `{` `}` must reach the registry as written.
			"globoff",
			`max-time = ${timeoutSeconds}`,
		];
		if (username || password) {
			lines.push(`user = ${curlConfigQuote(`${username ?? ""}:${password ?? ""}`)}`);
		}
		if (request.method === "HEAD") lines.push("head");
		if (request.method === "DELETE") lines.push('request = "DELETE"');
		if (request.manifest) {
			lines.push(`header = ${curlConfigQuote(`Accept: ${MANIFEST_ACCEPT}`)}`);
		}
		if (request.includeHeaders) lines.push("include");
		lines.push(`write-out = "\\n${RESPONSE_MARKER} ${request.id} %{http_code}\\n"`);
		return lines.join("\n");
	});
	return `${blocks.join("\nnext\n")}\n`;
};

/** Printed when the build server has no curl. */
export const NO_CURL_MARKER = "@@DPL-NOCURL";

/**
 * Command the build server runs. It carries no secret: curl reads its config,
 * credentials included, from stdin. Errors are dropped (the status code in the
 * output says what happened) and the exit status is always 0 so a refused
 * request is a result, not a failed command.
 */
export const REGISTRY_CURL_COMMAND = `command -v curl >/dev/null 2>&1 || { echo ${NO_CURL_MARKER}; exit 0; }; curl --config - 2>/dev/null; exit 0`;

export interface RegistryResponse {
	/** 0 when curl could not connect at all. */
	status: number;
	headers: Record<string, string>;
	body: string;
}

/** Reads the output of `REGISTRY_CURL_COMMAND` back into one response per request id. */
export const parseRegistryResponses = (stdout: string) => {
	const responses = new Map<number, RegistryResponse>();
	const marker = new RegExp(`${RESPONSE_MARKER} (\\d+) (\\d{3})\\r?\\n`, "g");
	let cursor = 0;
	for (let match = marker.exec(stdout); match; match = marker.exec(stdout)) {
		let segment = stdout.slice(cursor, match.index);
		cursor = match.index + match[0].length;
		// The write-out template starts with a newline of its own.
		if (segment.endsWith("\n")) segment = segment.slice(0, -1);
		let headers: Record<string, string> = {};
		let body = segment;
		if (/^HTTP\//.test(segment)) {
			const split = /\r?\n\r?\n/.exec(segment);
			const head = split ? segment.slice(0, split.index) : segment;
			body = split ? segment.slice(split.index + split[0].length) : "";
			headers = {};
			for (const line of head.split(/\r?\n/).slice(1)) {
				const colon = line.indexOf(":");
				if (colon > 0) {
					headers[line.slice(0, colon).trim().toLowerCase()] = line
						.slice(colon + 1)
						.trim();
				}
			}
		}
		responses.set(Number(match[1]), {
			status: Number(match[2]),
			headers,
			body,
		});
	}
	return responses;
};

export const getTagsListUrl = (base: string, repo: string) =>
	`${base}/v2/${repo}/tags/list?n=1000`;
export const getManifestUrl = (base: string, repo: string, reference: string) =>
	`${base}/v2/${repo}/manifests/${reference}`;
