version: '3.8'

services:
  meilisearch:
    networks:
      - dokploy-network
    image: getmeili/meilisearch:v1.8.3
    ports:
      - ${MEILISEARCH_PORT}
    volumes:
      - meili_data:/meili_data
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_ENV: ${MEILI_ENV}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${HASH}.rule=Host(`${MEILISEARCH_HOST}`)
      - traefik.http.services.${HASH}.loadbalancer.server.port=${MEILISEARCH_PORT}

volumes:
  meili_data:
    driver: local
networks:
  dokploy-network:
    external: true
