version: "3.8"
services:
  baserow:
    image: baserow/baserow:1.25.2
    networks:
      - dokploy-network
    environment:
      BASEROW_PUBLIC_URL: "http://${BASEROW_HOST}"
    ports:
      - ${BASEROW_PORT}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${HASH}.rule=Host(`${BASEROW_HOST}`)
      - traefik.http.services.${HASH}.loadbalancer.server.port=${BASEROW_PORT}
    volumes:
      - baserow_data:/baserow/data
volumes:
  baserow_data:

networks:
  dokploy-network:
    external: true