version: "3.8"
services:
  web:
    image: odoo:16.0
    networks:
      - dokploy-network
    depends_on:
      - db
    ports:
      - ${ODOO_PORT}
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${HASH}.rule=Host(`${ODOO_HOST}`)"
      - "traefik.http.services.${HASH}.loadbalancer.server.port=${ODOO_PORT}"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ../files/config:/etc/odoo
      - ../files/addons:/mnt/extra-addons

  db:
    image: postgres:13
    networks:
      - dokploy-network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  dokploy-network:
    external: true
