name: Bug Report
description: Create a bug report
labels: ["needs-triage🔍"]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue, please do a search of existing issues.

        If you need help with your own project, you can start a discussion in the [Q&A Section](https://github.com/Dokploy/dokploy/discussions).
  - type: textarea
    attributes:
      label: To Reproduce
      description: |
        A detailed, step-by-step description of how to reproduce the issue is required. 
        Please ensure your report includes clear instructions using numbered lists. 

        If possible, provide a link to a repository or project where the issue can be reproduced.
      placeholder: |
        1. Create a application
        2. Click X
        3. Y will happen

        Make sure to:
        - Use numbered lists to outline steps clearly.
        - Include all relevant commands and configurations.
        - Provide a link to a reproducible repository if applicable.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current vs. Expected behavior
      description: A clear and concise description of what the bug is, and what you expected to happen.
      placeholder: "Following the steps from the previous section, I expected A to happen, but I observed B instead"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Provide environment information
      description: Please provide the following information about your environment.
      render: bash
      placeholder: |
        Operating System:
          OS: Ubuntu 20.04
          Arch: arm64
        Dokploy version: 0.2.2'
        VPS Provider: DigitalOcean, Hetzner, Linode, etc.
        What applications/services are you tying to deploy?
         eg - Database, Nextjs App, laravel, etc.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Which area(s) are affected? (Select all that apply)
      multiple: true
      options:
        - "Installation"
        - "Application"
        - "Databases"
        - "Docker Compose"
        - "Traefik"
        - "Docker"
        - "Remote server"
        - "Local Development"
        - "Cloud Version"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Are you deploying the applications where Dokploy is installed or on a remote server?
      options:
        - "Same server where Dokploy is installed"
        - "Remote server"
        - "Both"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Any extra information that might help us investigate.
      placeholder: |
        I tested on a DigitalOcean VPS with Ubuntu 20.04 and Docker version 20.10.12.

  - type: dropdown
    attributes:
      label: Will you send a PR to fix it?
      description: Let us know if you are planning to submit a pull request to address this issue.

      options:
        - "Yes"
        - "No"
        - "Maybe, need help"
    validations:
      required: true
