services:
  actualbudget:
    image: docker.io/actualbudget/actual-server:latest
    environment:
      # See all options at https://actualbudget.org/docs/config
      - ACTUAL_PORT=5006
    volumes:
      - actual-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/5006' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  actual-data:
