version: "3.8"
services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    networks:
      - dokploy-network
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    environment:
      - "OLLAMA_BASE_URL=http://ollama:11434"
      - "WEBUI_SECRET_KEY="
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
