version: '3.8'
services:
  minio:
    image: minio/minio
    ports:
      - ${MINIO_API_PORT}
      - ${MINIO_DASHBOARD_PORT}
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    command: server /data --console-address ":9001"
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.${HASH}.service=${HASH}
      - traefik.http.routers.${HASH}.rule=Host(`${MINIO_DASHBOARD_HOST}`)
      - traefik.http.services.${HASH}.loadbalancer.server.port=${MINIO_DASHBOARD_PORT}
       # API router and service
      - traefik.http.routers.${HASH}-api.service=${HASH}-api
      - traefik.http.routers.${HASH}-api.rule=Host(`${MINIO_API_HOST}`)
      - traefik.http.services.${HASH}-api.loadbalancer.server.port=${MINIO_API_PORT}

volumes:
  minio-data:

networks:
  dokploy-network:
    external: true
