version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: tu_base_de_datos
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dokploy-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_ARBITRARY: 1
    ports:
      - ${PHPMYADMIN_PORT}
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.${HASH}.rule=Host(`${PHPMYADMIN_HOST}`)
      - traefik.http.services.${HASH}.loadbalancer.server.port=${PHPMYADMIN_PORT}
    networks:
      - dokploy-network

volumes:
  db_data:
    driver: local

networks:
  dokploy-network:
    external: true
