version: '3.8'

services:
  excalidraw:
    networks:
      - dokploy-network
    image: excalidraw/excalidraw:latest
    ports:
     - ${EXCALIDRAW_PORT}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${HASH}.rule=Host(`${EXCALIDRAW_HOST}`)
      - traefik.http.services.${HASH}.loadbalancer.server.port=${EXCALIDRAW_PORT}

networks:
  dokploy-network:
    external: true
