/* Autogenerated file. Do not edit manually. */

import en_us from './locales/en-us.json';
import zh_hans_cn from './locales/zh-hans-cn.json';

const locales = {
	'en-us': en_us,
	'zh-hans-cn': zh_hans_cn
};

export default locales;
