/* Autogenerated file. Do not edit manually. */

const locales = {
	'en-us': () => import('./locales/en-us.json').then(module => module.default),
	'zh-hans-cn': () => import('./locales/zh-hans-cn.json').then(module => module.default)
};

export default locales;
