version: '3.8'
services:
  wordpress:
    image: wordpress:5.8.3
    networks:
      - dokploy-network
    ports:
      - ${WORDPRESS_PORT}
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${HASH}.rule=Host(`${WORDPRESS_HOST}`)"
      - "traefik.http.services.${HASH}.loadbalancer.server.port=${WORDPRESS_PORT}"
    volumes:
      - wordpress_data:/var/www/html

  db:
    image: mysql:5.7.34
    networks:
      - dokploy-network
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:

networks:
  dokploy-network:
    external: true
