version: "3.8"
services:
  uptime-kuma:
    networks:
      - dokploy-network
    image: louislam/uptime-kuma:1
    restart: always
    ports:
      - ${UPTIME_KUMA_PORT}
    volumes:
      - uptime-kuma-data:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.${HASH}.rule=Host(`${UPTIME_KUMA_HOST}`)
      - traefik.http.services.${HASH}.loadbalancer.server.port=${UPTIME_KUMA_PORT}

volumes:
  uptime-kuma-data:
networks:
  dokploy-network:
    external: true