version: "3.8"
services:
  grafana:
    networks:
      - dokploy-network
    image: grafana/grafana-enterprise:9.5.20
    restart: unless-stopped
    ports:
     - ${GRAFANA_PORT}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${HASH}.rule=Host(`${GRAFANA_HOST}`)
      - traefik.http.services.${HASH}.loadbalancer.server.port=${GRAFANA_PORT}
    volumes:
      - grafana-storage:/var/lib/grafana
networks:
  dokploy-network:
    external: true
volumes:
  grafana-storage: {}