ALTER TABLE "postgres" ALTER COLUMN "memoryReservation" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "postgres" ALTER COLUMN "memoryLimit" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "postgres" ALTER COLUMN "cpuReservation" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "postgres" ALTER COLUMN "cpuLimit" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "mariadb" ALTER COLUMN "memoryReservation" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "mariadb" ALTER COLUMN "memoryLimit" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "mariadb" ALTER COLUMN "cpuReservation" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "mariadb" ALTER COLUMN "cpuLimit" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "mongo" ALTER COLUMN "memoryReservation" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "mongo" ALTER COLUMN "memoryLimit" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "mongo" ALTER COLUMN "cpuReservation" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "mongo" ALTER COLUMN "cpuLimit" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "mysql" ALTER COLUMN "memoryReservation" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "mysql" ALTER COLUMN "memoryLimit" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "mysql" ALTER COLUMN "cpuReservation" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "mysql" ALTER COLUMN "cpuLimit" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "redis" ALTER COLUMN "memoryReservation" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "redis" ALTER COLUMN "memoryLimit" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "redis" ALTER COLUMN "cpuReservation" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "redis" ALTER COLUMN "cpuLimit" SET DATA TYPE text;