// Complete list of IANA timezones grouped by region
export const TIMEZONES: Record<
	string,
	Array<{ label: string; value: string }>
> = {
	Common: [{ label: "UTC (Coordinated Universal Time)", value: "UTC" }],
	Africa: [
		{ label: "Abidjan", value: "Africa/Abidjan" },
		{ label: "Accra", value: "Africa/Accra" },
		{ label: "Addis Ababa", value: "Africa/Addis_Ababa" },
		{ label: "Algiers", value: "Africa/Algiers" },
		{ label: "Asmara", value: "Africa/Asmara" },
		{ label: "Bamako", value: "Africa/Bamako" },
		{ label: "Bangui", value: "Africa/Bangui" },
		{ label: "Banjul", value: "Africa/Banjul" },
		{ label: "Bissau", value: "Africa/Bissau" },
		{ label: "Blantyre", value: "Africa/Blantyre" },
		{ label: "Brazzaville", value: "Africa/Brazzaville" },
		{ label: "Bujumbura", value: "Africa/Bujumbura" },
		{ label: "Cairo", value: "Africa/Cairo" },
		{ label: "Casablanca", value: "Africa/Casablanca" },
		{ label: "Ceuta", value: "Africa/Ceuta" },
		{ label: "Conakry", value: "Africa/Conakry" },
		{ label: "Dakar", value: "Africa/Dakar" },
		{ label: "Dar es Salaam", value: "Africa/Dar_es_Salaam" },
		{ label: "Djibouti", value: "Africa/Djibouti" },
		{ label: "Douala", value: "Africa/Douala" },
		{ label: "El Aaiun", value: "Africa/El_Aaiun" },
		{ label: "Freetown", value: "Africa/Freetown" },
		{ label: "Gaborone", value: "Africa/Gaborone" },
		{ label: "Harare", value: "Africa/Harare" },
		{ label: "Johannesburg", value: "Africa/Johannesburg" },
		{ label: "Juba", value: "Africa/Juba" },
		{ label: "Kampala", value: "Africa/Kampala" },
		{ label: "Khartoum", value: "Africa/Khartoum" },
		{ label: "Kigali", value: "Africa/Kigali" },
		{ label: "Kinshasa", value: "Africa/Kinshasa" },
		{ label: "Lagos", value: "Africa/Lagos" },
		{ label: "Libreville", value: "Africa/Libreville" },
		{ label: "Lome", value: "Africa/Lome" },
		{ label: "Luanda", value: "Africa/Luanda" },
		{ label: "Lubumbashi", value: "Africa/Lubumbashi" },
		{ label: "Lusaka", value: "Africa/Lusaka" },
		{ label: "Malabo", value: "Africa/Malabo" },
		{ label: "Maputo", value: "Africa/Maputo" },
		{ label: "Maseru", value: "Africa/Maseru" },
		{ label: "Mbabane", value: "Africa/Mbabane" },
		{ label: "Mogadishu", value: "Africa/Mogadishu" },
		{ label: "Monrovia", value: "Africa/Monrovia" },
		{ label: "Nairobi", value: "Africa/Nairobi" },
		{ label: "Ndjamena", value: "Africa/Ndjamena" },
		{ label: "Niamey", value: "Africa/Niamey" },
		{ label: "Nouakchott", value: "Africa/Nouakchott" },
		{ label: "Ouagadougou", value: "Africa/Ouagadougou" },
		{ label: "Porto-Novo", value: "Africa/Porto-Novo" },
		{ label: "Sao Tome", value: "Africa/Sao_Tome" },
		{ label: "Tripoli", value: "Africa/Tripoli" },
		{ label: "Tunis", value: "Africa/Tunis" },
		{ label: "Windhoek", value: "Africa/Windhoek" },
	],
	America: [
		{ label: "Adak", value: "America/Adak" },
		{ label: "Anchorage", value: "America/Anchorage" },
		{ label: "Anguilla", value: "America/Anguilla" },
		{ label: "Antigua", value: "America/Antigua" },
		{ label: "Araguaina", value: "America/Araguaina" },
		{
			label: "Argentina/Buenos Aires",
			value: "America/Argentina/Buenos_Aires",
		},
		{ label: "Argentina/Catamarca", value: "America/Argentina/Catamarca" },
		{ label: "Argentina/Cordoba", value: "America/Argentina/Cordoba" },
		{ label: "Argentina/Jujuy", value: "America/Argentina/Jujuy" },
		{ label: "Argentina/La Rioja", value: "America/Argentina/La_Rioja" },
		{ label: "Argentina/Mendoza", value: "America/Argentina/Mendoza" },
		{
			label: "Argentina/Rio Gallegos",
			value: "America/Argentina/Rio_Gallegos",
		},
		{ label: "Argentina/Salta", value: "America/Argentina/Salta" },
		{ label: "Argentina/San Juan", value: "America/Argentina/San_Juan" },
		{ label: "Argentina/San Luis", value: "America/Argentina/San_Luis" },
		{ label: "Argentina/Tucuman", value: "America/Argentina/Tucuman" },
		{ label: "Argentina/Ushuaia", value: "America/Argentina/Ushuaia" },
		{ label: "Aruba", value: "America/Aruba" },
		{ label: "Asuncion", value: "America/Asuncion" },
		{ label: "Atikokan", value: "America/Atikokan" },
		{ label: "Bahia", value: "America/Bahia" },
		{ label: "Bahia Banderas", value: "America/Bahia_Banderas" },
		{ label: "Barbados", value: "America/Barbados" },
		{ label: "Belem", value: "America/Belem" },
		{ label: "Belize", value: "America/Belize" },
		{ label: "Blanc-Sablon", value: "America/Blanc-Sablon" },
		{ label: "Boa Vista", value: "America/Boa_Vista" },
		{ label: "Bogota", value: "America/Bogota" },
		{ label: "Boise", value: "America/Boise" },
		{ label: "Cambridge Bay", value: "America/Cambridge_Bay" },
		{ label: "Campo Grande", value: "America/Campo_Grande" },
		{ label: "Cancun", value: "America/Cancun" },
		{ label: "Caracas", value: "America/Caracas" },
		{ label: "Cayenne", value: "America/Cayenne" },
		{ label: "Cayman", value: "America/Cayman" },
		{ label: "Chicago (Central Time)", value: "America/Chicago" },
		{ label: "Chihuahua", value: "America/Chihuahua" },
		{ label: "Ciudad Juarez", value: "America/Ciudad_Juarez" },
		{ label: "Costa Rica", value: "America/Costa_Rica" },
		{ label: "Creston", value: "America/Creston" },
		{ label: "Cuiaba", value: "America/Cuiaba" },
		{ label: "Curacao", value: "America/Curacao" },
		{ label: "Danmarkshavn", value: "America/Danmarkshavn" },
		{ label: "Dawson", value: "America/Dawson" },
		{ label: "Dawson Creek", value: "America/Dawson_Creek" },
		{ label: "Denver (Mountain Time)", value: "America/Denver" },
		{ label: "Detroit", value: "America/Detroit" },
		{ label: "Dominica", value: "America/Dominica" },
		{ label: "Edmonton", value: "America/Edmonton" },
		{ label: "Eirunepe", value: "America/Eirunepe" },
		{ label: "El Salvador", value: "America/El_Salvador" },
		{ label: "Fort Nelson", value: "America/Fort_Nelson" },
		{ label: "Fortaleza", value: "America/Fortaleza" },
		{ label: "Glace Bay", value: "America/Glace_Bay" },
		{ label: "Goose Bay", value: "America/Goose_Bay" },
		{ label: "Grand Turk", value: "America/Grand_Turk" },
		{ label: "Grenada", value: "America/Grenada" },
		{ label: "Guadeloupe", value: "America/Guadeloupe" },
		{ label: "Guatemala", value: "America/Guatemala" },
		{ label: "Guayaquil", value: "America/Guayaquil" },
		{ label: "Guyana", value: "America/Guyana" },
		{ label: "Halifax", value: "America/Halifax" },
		{ label: "Havana", value: "America/Havana" },
		{ label: "Hermosillo", value: "America/Hermosillo" },
		{ label: "Indiana/Indianapolis", value: "America/Indiana/Indianapolis" },
		{ label: "Indiana/Knox", value: "America/Indiana/Knox" },
		{ label: "Indiana/Marengo", value: "America/Indiana/Marengo" },
		{ label: "Indiana/Petersburg", value: "America/Indiana/Petersburg" },
		{ label: "Indiana/Tell City", value: "America/Indiana/Tell_City" },
		{ label: "Indiana/Vevay", value: "America/Indiana/Vevay" },
		{ label: "Indiana/Vincennes", value: "America/Indiana/Vincennes" },
		{ label: "Indiana/Winamac", value: "America/Indiana/Winamac" },
		{ label: "Inuvik", value: "America/Inuvik" },
		{ label: "Iqaluit", value: "America/Iqaluit" },
		{ label: "Jamaica", value: "America/Jamaica" },
		{ label: "Juneau", value: "America/Juneau" },
		{ label: "Kentucky/Louisville", value: "America/Kentucky/Louisville" },
		{ label: "Kentucky/Monticello", value: "America/Kentucky/Monticello" },
		{ label: "Kralendijk", value: "America/Kralendijk" },
		{ label: "La Paz", value: "America/La_Paz" },
		{ label: "Lima", value: "America/Lima" },
		{ label: "Los Angeles (Pacific Time)", value: "America/Los_Angeles" },
		{ label: "Lower Princes", value: "America/Lower_Princes" },
		{ label: "Maceio", value: "America/Maceio" },
		{ label: "Managua", value: "America/Managua" },
		{ label: "Manaus", value: "America/Manaus" },
		{ label: "Marigot", value: "America/Marigot" },
		{ label: "Martinique", value: "America/Martinique" },
		{ label: "Matamoros", value: "America/Matamoros" },
		{ label: "Mazatlan", value: "America/Mazatlan" },
		{ label: "Menominee", value: "America/Menominee" },
		{ label: "Merida", value: "America/Merida" },
		{ label: "Metlakatla", value: "America/Metlakatla" },
		{ label: "Mexico City (Central Mexico)", value: "America/Mexico_City" },
		{ label: "Miquelon", value: "America/Miquelon" },
		{ label: "Moncton", value: "America/Moncton" },
		{ label: "Monterrey", value: "America/Monterrey" },
		{ label: "Montevideo", value: "America/Montevideo" },
		{ label: "Montserrat", value: "America/Montserrat" },
		{ label: "Nassau", value: "America/Nassau" },
		{ label: "New York (Eastern Time)", value: "America/New_York" },
		{ label: "Nome", value: "America/Nome" },
		{ label: "Noronha", value: "America/Noronha" },
		{ label: "North Dakota/Beulah", value: "America/North_Dakota/Beulah" },
		{ label: "North Dakota/Center", value: "America/North_Dakota/Center" },
		{
			label: "North Dakota/New Salem",
			value: "America/North_Dakota/New_Salem",
		},
		{ label: "Nuuk", value: "America/Nuuk" },
		{ label: "Ojinaga", value: "America/Ojinaga" },
		{ label: "Panama", value: "America/Panama" },
		{ label: "Paramaribo", value: "America/Paramaribo" },
		{ label: "Phoenix", value: "America/Phoenix" },
		{ label: "Port-au-Prince", value: "America/Port-au-Prince" },
		{ label: "Port of Spain", value: "America/Port_of_Spain" },
		{ label: "Porto Velho", value: "America/Porto_Velho" },
		{ label: "Puerto Rico", value: "America/Puerto_Rico" },
		{ label: "Punta Arenas", value: "America/Punta_Arenas" },
		{ label: "Rankin Inlet", value: "America/Rankin_Inlet" },
		{ label: "Recife", value: "America/Recife" },
		{ label: "Regina", value: "America/Regina" },
		{ label: "Resolute", value: "America/Resolute" },
		{ label: "Rio Branco", value: "America/Rio_Branco" },
		{ label: "Santarem", value: "America/Santarem" },
		{ label: "Santiago", value: "America/Santiago" },
		{ label: "Santo Domingo", value: "America/Santo_Domingo" },
		{ label: "Sao Paulo (Brasilia Time)", value: "America/Sao_Paulo" },
		{ label: "Scoresbysund", value: "America/Scoresbysund" },
		{ label: "Sitka", value: "America/Sitka" },
		{ label: "St Barthelemy", value: "America/St_Barthelemy" },
		{ label: "St Johns", value: "America/St_Johns" },
		{ label: "St Kitts", value: "America/St_Kitts" },
		{ label: "St Lucia", value: "America/St_Lucia" },
		{ label: "St Thomas", value: "America/St_Thomas" },
		{ label: "St Vincent", value: "America/St_Vincent" },
		{ label: "Swift Current", value: "America/Swift_Current" },
		{ label: "Tegucigalpa", value: "America/Tegucigalpa" },
		{ label: "Thule", value: "America/Thule" },
		{ label: "Tijuana", value: "America/Tijuana" },
		{ label: "Toronto", value: "America/Toronto" },
		{ label: "Tortola", value: "America/Tortola" },
		{ label: "Vancouver", value: "America/Vancouver" },
		{ label: "Whitehorse", value: "America/Whitehorse" },
		{ label: "Winnipeg", value: "America/Winnipeg" },
		{ label: "Yakutat", value: "America/Yakutat" },
	],
	Antarctica: [
		{ label: "Casey", value: "Antarctica/Casey" },
		{ label: "Davis", value: "Antarctica/Davis" },
		{ label: "DumontDUrville", value: "Antarctica/DumontDUrville" },
		{ label: "Macquarie", value: "Antarctica/Macquarie" },
		{ label: "Mawson", value: "Antarctica/Mawson" },
		{ label: "McMurdo", value: "Antarctica/McMurdo" },
		{ label: "Palmer", value: "Antarctica/Palmer" },
		{ label: "Rothera", value: "Antarctica/Rothera" },
		{ label: "Syowa", value: "Antarctica/Syowa" },
		{ label: "Troll", value: "Antarctica/Troll" },
		{ label: "Vostok", value: "Antarctica/Vostok" },
	],
	Arctic: [{ label: "Longyearbyen", value: "Arctic/Longyearbyen" }],
	Asia: [
		{ label: "Aden", value: "Asia/Aden" },
		{ label: "Almaty", value: "Asia/Almaty" },
		{ label: "Amman", value: "Asia/Amman" },
		{ label: "Anadyr", value: "Asia/Anadyr" },
		{ label: "Aqtau", value: "Asia/Aqtau" },
		{ label: "Aqtobe", value: "Asia/Aqtobe" },
		{ label: "Ashgabat", value: "Asia/Ashgabat" },
		{ label: "Atyrau", value: "Asia/Atyrau" },
		{ label: "Baghdad", value: "Asia/Baghdad" },
		{ label: "Bahrain", value: "Asia/Bahrain" },
		{ label: "Baku", value: "Asia/Baku" },
		{ label: "Bangkok", value: "Asia/Bangkok" },
		{ label: "Barnaul", value: "Asia/Barnaul" },
		{ label: "Beirut", value: "Asia/Beirut" },
		{ label: "Bishkek", value: "Asia/Bishkek" },
		{ label: "Brunei", value: "Asia/Brunei" },
		{ label: "Chita", value: "Asia/Chita" },
		{ label: "Choibalsan", value: "Asia/Choibalsan" },
		{ label: "Colombo", value: "Asia/Colombo" },
		{ label: "Damascus", value: "Asia/Damascus" },
		{ label: "Dhaka", value: "Asia/Dhaka" },
		{ label: "Dili", value: "Asia/Dili" },
		{ label: "Dubai (Gulf Standard Time)", value: "Asia/Dubai" },
		{ label: "Dushanbe", value: "Asia/Dushanbe" },
		{ label: "Famagusta", value: "Asia/Famagusta" },
		{ label: "Gaza", value: "Asia/Gaza" },
		{ label: "Hebron", value: "Asia/Hebron" },
		{ label: "Ho Chi Minh", value: "Asia/Ho_Chi_Minh" },
		{ label: "Hong Kong", value: "Asia/Hong_Kong" },
		{ label: "Hovd", value: "Asia/Hovd" },
		{ label: "Irkutsk", value: "Asia/Irkutsk" },
		{ label: "Jakarta", value: "Asia/Jakarta" },
		{ label: "Jayapura", value: "Asia/Jayapura" },
		{ label: "Jerusalem", value: "Asia/Jerusalem" },
		{ label: "Kabul", value: "Asia/Kabul" },
		{ label: "Kamchatka", value: "Asia/Kamchatka" },
		{ label: "Karachi", value: "Asia/Karachi" },
		{ label: "Kathmandu", value: "Asia/Kathmandu" },
		{ label: "Khandyga", value: "Asia/Khandyga" },
		{ label: "Kolkata (India Standard Time)", value: "Asia/Kolkata" },
		{ label: "Krasnoyarsk", value: "Asia/Krasnoyarsk" },
		{ label: "Kuala Lumpur", value: "Asia/Kuala_Lumpur" },
		{ label: "Kuching", value: "Asia/Kuching" },
		{ label: "Kuwait", value: "Asia/Kuwait" },
		{ label: "Macau", value: "Asia/Macau" },
		{ label: "Magadan", value: "Asia/Magadan" },
		{ label: "Makassar", value: "Asia/Makassar" },
		{ label: "Manila", value: "Asia/Manila" },
		{ label: "Muscat", value: "Asia/Muscat" },
		{ label: "Nicosia", value: "Asia/Nicosia" },
		{ label: "Novokuznetsk", value: "Asia/Novokuznetsk" },
		{ label: "Novosibirsk", value: "Asia/Novosibirsk" },
		{ label: "Omsk", value: "Asia/Omsk" },
		{ label: "Oral", value: "Asia/Oral" },
		{ label: "Phnom Penh", value: "Asia/Phnom_Penh" },
		{ label: "Pontianak", value: "Asia/Pontianak" },
		{ label: "Pyongyang", value: "Asia/Pyongyang" },
		{ label: "Qatar", value: "Asia/Qatar" },
		{ label: "Qostanay", value: "Asia/Qostanay" },
		{ label: "Qyzylorda", value: "Asia/Qyzylorda" },
		{ label: "Riyadh", value: "Asia/Riyadh" },
		{ label: "Sakhalin", value: "Asia/Sakhalin" },
		{ label: "Samarkand", value: "Asia/Samarkand" },
		{ label: "Seoul", value: "Asia/Seoul" },
		{ label: "Shanghai (China Standard Time)", value: "Asia/Shanghai" },
		{ label: "Singapore", value: "Asia/Singapore" },
		{ label: "Srednekolymsk", value: "Asia/Srednekolymsk" },
		{ label: "Taipei", value: "Asia/Taipei" },
		{ label: "Tashkent", value: "Asia/Tashkent" },
		{ label: "Tbilisi", value: "Asia/Tbilisi" },
		{ label: "Tehran", value: "Asia/Tehran" },
		{ label: "Thimphu", value: "Asia/Thimphu" },
		{ label: "Tokyo (Japan Standard Time)", value: "Asia/Tokyo" },
		{ label: "Tomsk", value: "Asia/Tomsk" },
		{ label: "Ulaanbaatar", value: "Asia/Ulaanbaatar" },
		{ label: "Urumqi", value: "Asia/Urumqi" },
		{ label: "Ust-Nera", value: "Asia/Ust-Nera" },
		{ label: "Vientiane", value: "Asia/Vientiane" },
		{ label: "Vladivostok", value: "Asia/Vladivostok" },
		{ label: "Yakutsk", value: "Asia/Yakutsk" },
		{ label: "Yangon", value: "Asia/Yangon" },
		{ label: "Yekaterinburg", value: "Asia/Yekaterinburg" },
		{ label: "Yerevan", value: "Asia/Yerevan" },
	],
	Atlantic: [
		{ label: "Azores", value: "Atlantic/Azores" },
		{ label: "Bermuda", value: "Atlantic/Bermuda" },
		{ label: "Canary", value: "Atlantic/Canary" },
		{ label: "Cape Verde", value: "Atlantic/Cape_Verde" },
		{ label: "Faroe", value: "Atlantic/Faroe" },
		{ label: "Madeira", value: "Atlantic/Madeira" },
		{ label: "Reykjavik", value: "Atlantic/Reykjavik" },
		{ label: "South Georgia", value: "Atlantic/South_Georgia" },
		{ label: "St Helena", value: "Atlantic/St_Helena" },
		{ label: "Stanley", value: "Atlantic/Stanley" },
	],
	Australia: [
		{ label: "Adelaide", value: "Australia/Adelaide" },
		{ label: "Brisbane", value: "Australia/Brisbane" },
		{ label: "Broken Hill", value: "Australia/Broken_Hill" },
		{ label: "Darwin", value: "Australia/Darwin" },
		{ label: "Eucla", value: "Australia/Eucla" },
		{ label: "Hobart", value: "Australia/Hobart" },
		{ label: "Lindeman", value: "Australia/Lindeman" },
		{ label: "Lord Howe", value: "Australia/Lord_Howe" },
		{ label: "Melbourne", value: "Australia/Melbourne" },
		{ label: "Perth", value: "Australia/Perth" },
		{ label: "Sydney (Australian Eastern Time)", value: "Australia/Sydney" },
	],
	Europe: [
		{ label: "Amsterdam", value: "Europe/Amsterdam" },
		{ label: "Andorra", value: "Europe/Andorra" },
		{ label: "Astrakhan", value: "Europe/Astrakhan" },
		{ label: "Athens", value: "Europe/Athens" },
		{ label: "Belgrade", value: "Europe/Belgrade" },
		{ label: "Berlin (Central European Time)", value: "Europe/Berlin" },
		{ label: "Bratislava", value: "Europe/Bratislava" },
		{ label: "Brussels", value: "Europe/Brussels" },
		{ label: "Bucharest", value: "Europe/Bucharest" },
		{ label: "Budapest", value: "Europe/Budapest" },
		{ label: "Busingen", value: "Europe/Busingen" },
		{ label: "Chisinau", value: "Europe/Chisinau" },
		{ label: "Copenhagen", value: "Europe/Copenhagen" },
		{ label: "Dublin", value: "Europe/Dublin" },
		{ label: "Gibraltar", value: "Europe/Gibraltar" },
		{ label: "Guernsey", value: "Europe/Guernsey" },
		{ label: "Helsinki", value: "Europe/Helsinki" },
		{ label: "Isle of Man", value: "Europe/Isle_of_Man" },
		{ label: "Istanbul", value: "Europe/Istanbul" },
		{ label: "Jersey", value: "Europe/Jersey" },
		{ label: "Kaliningrad", value: "Europe/Kaliningrad" },
		{ label: "Kirov", value: "Europe/Kirov" },
		{ label: "Kyiv", value: "Europe/Kyiv" },
		{ label: "Lisbon", value: "Europe/Lisbon" },
		{ label: "Ljubljana", value: "Europe/Ljubljana" },
		{ label: "London (Greenwich Mean Time)", value: "Europe/London" },
		{ label: "Luxembourg", value: "Europe/Luxembourg" },
		{ label: "Madrid", value: "Europe/Madrid" },
		{ label: "Malta", value: "Europe/Malta" },
		{ label: "Mariehamn", value: "Europe/Mariehamn" },
		{ label: "Minsk", value: "Europe/Minsk" },
		{ label: "Monaco", value: "Europe/Monaco" },
		{ label: "Moscow", value: "Europe/Moscow" },
		{ label: "Oslo", value: "Europe/Oslo" },
		{ label: "Paris (Central European Time)", value: "Europe/Paris" },
		{ label: "Podgorica", value: "Europe/Podgorica" },
		{ label: "Prague", value: "Europe/Prague" },
		{ label: "Riga", value: "Europe/Riga" },
		{ label: "Rome", value: "Europe/Rome" },
		{ label: "Samara", value: "Europe/Samara" },
		{ label: "San Marino", value: "Europe/San_Marino" },
		{ label: "Sarajevo", value: "Europe/Sarajevo" },
		{ label: "Saratov", value: "Europe/Saratov" },
		{ label: "Simferopol", value: "Europe/Simferopol" },
		{ label: "Skopje", value: "Europe/Skopje" },
		{ label: "Sofia", value: "Europe/Sofia" },
		{ label: "Stockholm", value: "Europe/Stockholm" },
		{ label: "Tallinn", value: "Europe/Tallinn" },
		{ label: "Tirane", value: "Europe/Tirane" },
		{ label: "Ulyanovsk", value: "Europe/Ulyanovsk" },
		{ label: "Vaduz", value: "Europe/Vaduz" },
		{ label: "Vatican", value: "Europe/Vatican" },
		{ label: "Vienna", value: "Europe/Vienna" },
		{ label: "Vilnius", value: "Europe/Vilnius" },
		{ label: "Volgograd", value: "Europe/Volgograd" },
		{ label: "Warsaw", value: "Europe/Warsaw" },
		{ label: "Zagreb", value: "Europe/Zagreb" },
		{ label: "Zurich", value: "Europe/Zurich" },
	],
	Indian: [
		{ label: "Antananarivo", value: "Indian/Antananarivo" },
		{ label: "Chagos", value: "Indian/Chagos" },
		{ label: "Christmas", value: "Indian/Christmas" },
		{ label: "Cocos", value: "Indian/Cocos" },
		{ label: "Comoro", value: "Indian/Comoro" },
		{ label: "Kerguelen", value: "Indian/Kerguelen" },
		{ label: "Mahe", value: "Indian/Mahe" },
		{ label: "Maldives", value: "Indian/Maldives" },
		{ label: "Mauritius", value: "Indian/Mauritius" },
		{ label: "Mayotte", value: "Indian/Mayotte" },
		{ label: "Reunion", value: "Indian/Reunion" },
	],
	Pacific: [
		{ label: "Apia", value: "Pacific/Apia" },
		{ label: "Auckland", value: "Pacific/Auckland" },
		{ label: "Bougainville", value: "Pacific/Bougainville" },
		{ label: "Chatham", value: "Pacific/Chatham" },
		{ label: "Chuuk", value: "Pacific/Chuuk" },
		{ label: "Easter", value: "Pacific/Easter" },
		{ label: "Efate", value: "Pacific/Efate" },
		{ label: "Fakaofo", value: "Pacific/Fakaofo" },
		{ label: "Fiji", value: "Pacific/Fiji" },
		{ label: "Funafuti", value: "Pacific/Funafuti" },
		{ label: "Galapagos", value: "Pacific/Galapagos" },
		{ label: "Gambier", value: "Pacific/Gambier" },
		{ label: "Guadalcanal", value: "Pacific/Guadalcanal" },
		{ label: "Guam", value: "Pacific/Guam" },
		{ label: "Honolulu", value: "Pacific/Honolulu" },
		{ label: "Kanton", value: "Pacific/Kanton" },
		{ label: "Kiritimati", value: "Pacific/Kiritimati" },
		{ label: "Kosrae", value: "Pacific/Kosrae" },
		{ label: "Kwajalein", value: "Pacific/Kwajalein" },
		{ label: "Majuro", value: "Pacific/Majuro" },
		{ label: "Marquesas", value: "Pacific/Marquesas" },
		{ label: "Midway", value: "Pacific/Midway" },
		{ label: "Nauru", value: "Pacific/Nauru" },
		{ label: "Niue", value: "Pacific/Niue" },
		{ label: "Norfolk", value: "Pacific/Norfolk" },
		{ label: "Noumea", value: "Pacific/Noumea" },
		{ label: "Pago Pago", value: "Pacific/Pago_Pago" },
		{ label: "Palau", value: "Pacific/Palau" },
		{ label: "Pitcairn", value: "Pacific/Pitcairn" },
		{ label: "Pohnpei", value: "Pacific/Pohnpei" },
		{ label: "Port Moresby", value: "Pacific/Port_Moresby" },
		{ label: "Rarotonga", value: "Pacific/Rarotonga" },
		{ label: "Saipan", value: "Pacific/Saipan" },
		{ label: "Tahiti", value: "Pacific/Tahiti" },
		{ label: "Tarawa", value: "Pacific/Tarawa" },
		{ label: "Tongatapu", value: "Pacific/Tongatapu" },
		{ label: "Wake", value: "Pacific/Wake" },
		{ label: "Wallis", value: "Pacific/Wallis" },
	],
};

// Helper to get display label for a timezone value
export function getTimezoneLabel(value: string | undefined): string {
	if (!value) return "UTC (default)";
	return value;
}
