services:
  pocketbase:
    image: spectado/pocketbase:latest
    restart: unless-stopped
    volumes:
      - /etc/dokploy/templates/${HASH}/data:/pb_data
      - /etc/dokploy/templates/${HASH}/public:/pb_public
      - /etc/dokploy/templates/${HASH}/migrations:/pb_migrations
