services:
  gotenberg:
    image: gotenberg/gotenberg:latest
    environment:
      # NOTE: requires the --api-enable-basic-auth option in "command"
      GOTENBERG_API_BASIC_AUTH_USERNAME: ${GOTENBERG_API_BASIC_AUTH_USERNAME}
      GOTENBERG_API_BASIC_AUTH_PASSWORD: ${GOTENBERG_API_BASIC_AUTH_PASSWORD}
    command:
      - gotenberg
      # See the full list of options at https://gotenberg.dev/docs/configuration
      - "--api-enable-basic-auth"
      # - "--api-timeout=60s"
      # - "--chromium-auto-start"

    # If you want to horizontally scale gotenberg
    #deploy:
    #  replicas: 3
    #  restart_policy:
    #    condition: on-failure

    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  dokploy-network:
    external: true
