name: autofix.ci

on:
  push:
    branches: [canary]
  pull_request:
    branches: [canary]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup biomeJs
        uses: biomejs/setup-biome@v2  

      - name: Run Biome formatter
        run:  biome format --write

      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27 # v1.3.2
